using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Vampire.UI;

[GenerateTypedNameReferences]
public sealed partial class VampireDeadUI : FancyWindow
{
    public VampireDeadUI()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Close();
    }
}
