- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 #Imperial role timers
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External
  extendedAccess:
  - Chemistry
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction
  - skillPharmacology
  - skillMedicalEquipment


- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltParamedicFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
