using System.Collections.Generic;
using Content.Shared._CorvaxGoob.FaxTracker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CorvaxGoob.FaxTracker;

[GenerateTypedNameReferences]
public sealed partial class FaxTrackerUiFragment : BoxContainer
{
    [Dependency] private readonly IClipboardManager _clipboard = null!;

    public event Action? OnClearPressed;
    public event Action? OnNotificationPressed;
    public event Action<int>? OnEntryRemovePressed;
    public event Action<int>? OnEntryFavoritePressed;
    public event Action<string>? OnBlacklistAdd;
    public event Action<string>? OnBlacklistRemove;

    private const int MaxTitleChars = 40;

    private List<FaxTrackerEntry> _entries = new List<FaxTrackerEntry>();
    private int _index;
    private string? _shownText;
    private bool _showBlacklist;

    public FaxTrackerUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ClearButton.OnPressed += _ => OnClearPressed?.Invoke();
        NotificationButton.OnPressed += _ => OnNotificationPressed?.Invoke();
        BlacklistTabButton.OnToggled += args =>
        {
            _showBlacklist = args.Pressed;
            UpdateView();
        };

        PrevButton.OnPressed += _ =>
        {
            if (_index < _entries.Count - 1)
            {
                _index++;
                ShowCurrent();
            }
        };
        NextButton.OnPressed += _ =>
        {
            if (_index > 0)
            {
                _index--;
                ShowCurrent();
            }
        };

        FavoriteButton.OnPressed += _ =>
        {
            if (TryGetCurrent(out var entry))
                OnEntryFavoritePressed?.Invoke(entry.Number);
        };
        RemoveButton.OnPressed += _ =>
        {
            if (TryGetCurrent(out var entry))
                OnEntryRemovePressed?.Invoke(entry.Number);
        };
        CopyButton.OnPressed += _ =>
        {
            if (_shownText != null)
                _clipboard.SetText(_shownText);
        };

        PositionEdit.OnTextEntered += OnPositionEntered;

        UpdateView();
    }

    private void OnPositionEntered(LineEdit.LineEditEventArgs args)
    {
        if (int.TryParse(args.Text, out var number) && _entries.Count > 0)
            _index = _entries.Count - Math.Clamp(number, 1, _entries.Count);

        ShowCurrent();
    }

    public void UpdateState(FaxTrackerUiState state)
    {
        BellMutedIcon.Visible = !state.NotificationsOn;

        StatusLabel.Text = state.Bound
            ? Loc.GetString("fax-tracker-ui-bound", ("fax", state.FaxName ?? string.Empty))
            : Loc.GetString("fax-tracker-ui-not-bound");

        int? openNumber = null;
        if (TryGetCurrent(out var current))
            openNumber = current.Number;

        _entries = state.Entries;

        var has = _entries.Count > 0;
        ClearButton.Disabled = !has;
        FavoriteButton.Disabled = !has;
        RemoveButton.Disabled = !has;
        CopyButton.Disabled = !has;
        PositionEdit.Editable = has;

        if (has)
        {
            if (openNumber != null)
                _index = _entries.FindIndex(e => e.Number == openNumber.Value);
            else
                _index = 0;

            if (_index < 0)
                _index = 0;

            ShowCurrent();
        }
        else
        {
            _index = 0;
            ShowEmpty();
        }

        RebuildBlacklist(state);
    }

    private void UpdateView()
    {
        MessageView.Visible = !_showBlacklist;
        BlacklistView.Visible = _showBlacklist;
        BlacklistTabButton.Pressed = _showBlacklist;
    }

    private void RebuildBlacklist(FaxTrackerUiState state)
    {
        KnownFaxList.RemoveAllChildren();
        foreach (var sender in state.KnownFaxes)
        {
            var address = sender.Address;
            var button = new Button
            {
                Text = sender.Name,
                Margin = new Thickness(0, 0, 0, 2),
                ToolTip = Loc.GetString("fax-tracker-ui-blacklist-add-tooltip", ("sender", sender.Name)),
            };
            button.OnPressed += _ => OnBlacklistAdd?.Invoke(address);
            KnownFaxList.AddChild(button);
        }

        if (state.KnownFaxes.Count == 0)
            KnownFaxList.AddChild(new Label { Text = Loc.GetString("fax-tracker-ui-blacklist-known-empty"), StyleClasses = { "LabelSubText" } });

        BlacklistList.RemoveAllChildren();
        foreach (var sender in state.Blacklist)
        {
            var address = sender.Address;
            var button = new Button
            {
                Text = $"✕ {sender.Name}",
                StyleClasses = { "Caution" },
                Margin = new Thickness(0, 0, 0, 2),
                ToolTip = Loc.GetString("fax-tracker-ui-blacklist-remove-tooltip", ("sender", sender.Name)),
            };
            button.OnPressed += _ => OnBlacklistRemove?.Invoke(address);
            BlacklistList.AddChild(button);
        }

        if (state.Blacklist.Count == 0)
            BlacklistList.AddChild(new Label { Text = Loc.GetString("fax-tracker-ui-blacklist-blocked-empty"), StyleClasses = { "LabelSubText" } });
    }

    private bool TryGetCurrent(out FaxTrackerEntry entry)
    {
        if (_entries.Count > 0 && _index < _entries.Count)
        {
            entry = _entries[_index];
            return true;
        }

        entry = default;
        return false;
    }

    private void ShowEmpty()
    {
        _shownText = null;

        PrevButton.Disabled = true;
        NextButton.Disabled = true;

        HeaderLabel.Text = string.Empty;
        PositionEdit.Text = string.Empty;
        PositionTotalLabel.Text = string.Empty;

        ContentLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("fax-tracker-ui-empty")));
    }

    private void ShowCurrent()
    {
        if (!TryGetCurrent(out var entry))
            return;

        var time = entry.Time.ToString(@"hh\:mm\:ss");
        if (string.IsNullOrWhiteSpace(entry.Title))
        {
            HeaderLabel.Text = Loc.GetString("fax-tracker-ui-entry", ("time", time), ("number", entry.Number));
        }
        else
        {
            var title = entry.Title!;
            if (title.Length > MaxTitleChars)
                title = title.Substring(0, MaxTitleChars).TrimEnd() + "…";

            HeaderLabel.Text = Loc.GetString("fax-tracker-ui-entry-named", ("time", time), ("name", title));
        }

        PositionEdit.Text = (_entries.Count - _index).ToString();
        PositionTotalLabel.Text = Loc.GetString("fax-tracker-ui-position-total", ("total", _entries.Count));

        FavoriteButton.Text = Loc.GetString(entry.IsFavorite
            ? "fax-tracker-ui-entry-favorite-on"
            : "fax-tracker-ui-entry-favorite-off");

        PrevButton.Disabled = _index >= _entries.Count - 1;
        NextButton.Disabled = _index <= 0;

        ShowContent(entry);
    }

    private void ShowContent(FaxTrackerEntry entry)
    {
        _shownText = entry.Content;

        var msg = new FormattedMessage();

        if (!string.IsNullOrWhiteSpace(entry.SenderName))
        {
            msg.AddMarkupPermissive(Loc.GetString("fax-tracker-ui-from"));
            msg.AddText(" " + entry.SenderName);
            msg.PushNewline();
            msg.PushNewline();
        }

        msg.AddMarkupPermissive(entry.Content);

        if (entry.Stamps.Count > 0)
        {
            msg.PushNewline();
            msg.PushNewline();
            msg.AddMarkupPermissive(Loc.GetString("fax-tracker-ui-stamps"));

            for (var i = 0; i < entry.Stamps.Count; i++)
            {
                var stamp = entry.Stamps[i];
                msg.AddText(i == 0 ? " " : ", ");
                msg.AddMarkupPermissive($"[color={stamp.StampedColor.ToHex()}]{Loc.GetString(stamp.StampedName)}[/color]");
            }
        }

        ContentLabel.SetMessage(msg);
    }
}
