using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas volume pump.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class HydrogenVolumePumpWindow : FancyWindow
    {
        public event Action<bool>? ToggleStatusButtonPressed;
        public event Action<string>? PumpTransferRateChanged;

        public HydrogenVolumePumpWindow()
        {
            RobustXamlLoader.Load(this);

            ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

            PumpTransferRateInput.OnTextChanged += _ => SetTransferRateButton.Disabled = false;
            SetTransferRateButton.OnPressed += _ =>
            {
                PumpTransferRateChanged?.Invoke(PumpTransferRateInput.Text ??= "");
                SetTransferRateButton.Disabled = true;
            };

            SetMaxRateButton.OnPressed += _ =>
            {
                PumpTransferRateInput.Text = Atmospherics.HydrogenMaxTransferRate.ToString(CultureInfo.CurrentCulture);
                SetTransferRateButton.Disabled = false;
            };
        }

        public void SetTransferRate(float rate)
        {
            PumpTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
        }

        public void SetPumpStatus(bool enabled)
        {
            ToggleStatusButton.Pressed = enabled;
        }
    }
}
