using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.DecalGun;

/// <summary>
/// A client-side user interface window for configuring and previewing decal placement using the decal gun.
/// Provides controls to select a decal prototype, customize its color, rotation, placement behavior (snap to tile),
/// and cleanability. Updates are sent to the server through a callback delegate.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DecalGunWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    /// <summary>
    /// Invoked when the user changes the decal configuration (selection, color, rotation, etc.).
    /// </summary>
    public Action<string, Color, bool, float, bool>? OnSelectionChanged;

    private readonly SpriteSystem _sprite;

    public FloatSpinBox RotationSpinBox;
    private SortedDictionary<string, Texture>? _decals;
    private string? _selected;
    private bool _snap;
    private Color _color = Color.White;
    private float _rotation;
    private bool _isCleanable;

    public DecalGunWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();

        Search.OnTextChanged += _ => RefreshList();
        ColorPicker.OnColorChanged += OnColorPicked;

        RotationSpinBox = new FloatSpinBox(90.0f, 0)
        {
            HorizontalExpand = true
        };
        SpinBoxContainer.AddChild(RotationSpinBox);

        EnableSnap.OnToggled += args =>
        {
            _snap = args.Pressed;
            UpdateDecalPlacementInfo();
        };

        RotationSpinBox.OnValueChanged += args =>
        {
            _rotation = args.Value;
            UpdateDecalPlacementInfo();
        };

        EnableCleanable.OnToggled += args =>
        {
            _isCleanable = args.Pressed;
            UpdateDecalPlacementInfo();
        };
    }

    private void OnColorPicked(Color color)
    {
        _color = color;
        UpdateDecalPlacementInfo();
        RefreshList();
    }

    private void UpdateDecalPlacementInfo()
    {
        if (_selected is null)
            return;

        var color = _color;

        OnSelectionChanged?.Invoke(_selected, color, _snap, _rotation, _isCleanable);
    }

    private void RefreshList()
    {
        Grid.RemoveAllChildren();

        if (_decals == null)
            return;

        var filter = Search.Text;
        foreach (var (decal, tex) in _decals)
        {
            if (!decal.Contains(filter, StringComparison.InvariantCultureIgnoreCase))
                continue;

            var button = new TextureButton
            {
                TextureNormal = tex,
                Name = decal,
                ToolTip = decal,
                Modulate = _color,
            };
            button.OnPressed += ButtonOnPressed;
            if (_selected == decal)
            {
                var panelContainer = new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = StyleNano.ButtonColorDefault,
                    },
                    Children =
                    {
                        button,
                    },
                };
                Grid.AddChild(panelContainer);
            }
            else
                Grid.AddChild(button);
        }
    }

    private void ButtonOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (obj.Button.Name == null)
            return;

        SelectDecal(obj.Button.Name);
    }

    private void SelectDecal(string decalId)
    {
        if (!_proto.TryIndex<DecalPrototype>(decalId, out _))
            return;

        _selected = decalId;

        UpdateDecalPlacementInfo();
        RefreshList();
    }

    /// <summary>
    /// Populates the window's decal list with available prototypes.
    /// </summary>
    public void Populate(HashSet<DecalPrototype> prototypes)
    {
        _decals = new SortedDictionary<string, Texture>();
        foreach (var decalPrototype in prototypes)
        {
            _decals.Add(decalPrototype.ID, _sprite.Frame0(decalPrototype.Sprite));
        }

        RefreshList();
    }

    /// <summary>
    /// Applies decal configuration from the server state to the UI.
    /// </summary>
    public void SetData(string decal, Color color, bool snap, float rotation, bool isCleanable)
    {
        _selected = decal;
        _color = color;
        _snap = snap;
        _rotation = rotation;
        _isCleanable = isCleanable;

        EnableSnap.Pressed = snap;
        ColorPicker.Color = color;
        RotationSpinBox.Value = rotation;
        EnableCleanable.Pressed = isCleanable;

        RefreshList();
    }
}

