using System.Linq;
using Content.Client.Computer;
using Content.Client.UserInterface;
using Content.Shared.Imperial.EnergyCore;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.EnergyCore.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CoreTerminalWindow : DefaultWindow
    {
        public event Action<UiButton>? OnCoreTerminalButton;

        public CoreTerminalWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            AutoButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.Auto);
            RiseTempButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.RiseTemp);
            CoolTempButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.CoolTemp);

            UpReactivityButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.UpReactivity);
            DownReactivityButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.DownReactivity);
            UpHalflifeButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.UpHalflife);
            DownHalflifeButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.DownHalflife);
        }
        /*
                public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
                {
                    CoreReactivity.OnTextEntered += text =>
                    {
                        if (!float.TryParse((string?)text.Text, out var value))
                            return;

                        CoreLineEditAdjustMessage msg = new()
                        {
                            ReactivityMsg = (float)value,
                        };
                        cb.SendMessage(msg);
                    };

                    CoreHalflife.OnTextEntered += text =>
                    {
                        if (!float.TryParse((string?)text.Text, out var value))
                            return;

                        CoreLineEditAdjustMessage msg = new()
                        {
                            HalflifeMsg = (float)value,
                        };
                        cb.SendMessage(msg);
                    };
                }
        */
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (CoreTerminalBoundUserInterfaceState)state;

            CurrentCoreStatus.Text = $"{castState.CoreStatus}";

            if (castState.TempRising)
                SafeProtocolStatus.Text = Loc.GetString("temp-rise-true");
            else
                SafeProtocolStatus.Text = Loc.GetString("temp-rise-false");

            if (castState.SafeProtocol)
                SafeProtocolStatus.Text = Loc.GetString("status-active");
            else
                SafeProtocolStatus.Text = Loc.GetString("status-inactive");

            if (castState.AutoSystem == 2)
                AutoStatus.Text = Loc.GetString("status-active");
            else
                AutoStatus.Text = Loc.GetString("status-inactive");

            CurrentTemp.Text = $"{castState.CoreTemp}";
            CoreTempCoef.Text = $"{castState.TempChangeCoef}";
            CurrentPowerSupply.Text = $"{castState.CurrentPowerSupply:N1}";
        }
    }
}
