using System.Linq;
using Content.Client.Computer;
using Content.Client.UserInterface;
using Content.Shared.Imperial.EnergyCore;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.EnergyCore.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CoreTerminalWindow : DefaultWindow
    {
        public event Action<UiButton>? OnCoreTerminalButton;

        public CoreTerminalWindow()
        {
            RobustXamlLoader.Load(this);

            AutoButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.Auto);
            RiseTempButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.RiseTemp);
            CoolTempButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.CoolTemp);

            UpReactivityButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.UpReactivity);
            DownReactivityButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.DownReactivity);
            UpHalflifeButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.UpHalflife);
            DownHalflifeButton.OnPressed += _ => OnCoreTerminalButton?.Invoke(UiButton.DownHalflife);
        }
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (CoreTerminalBoundUserInterfaceState)state;

            CurrentCoreStatus.Text = Loc.GetString($"energycore-status-{castState.Status.ToString().ToLower()}");
            RiseStatus.Text = Loc.GetString($"temp-rise-{castState.AutoSystem.ToString().ToLower()}");
            SafeProtocolStatus.Text = Loc.GetString($"core-protocol-{castState.SafeProtocol.ToString().ToLower()}");

            if (castState.AutoSystem == CoreTempChangeLevel.AUTO)
                AutoStatus.Text = Loc.GetString("status-active");
            else
                AutoStatus.Text = Loc.GetString("status-inactive");

            CurrentTemp.Text = $"{castState.CoreTemp:N1}";
            CoreTempCoef.Text = $"{castState.TempChangeCoef:N1}";
        }
    }
}
