// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._CorvaxGoob.Radio;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CorvaxGoob.Radio.UI;

[GenerateTypedNameReferences]
public sealed partial class HeadsetMenu : FancyWindow
{
    private const float CheckColumnWidth = 72f;

    [Dependency] private IPrototypeManager _prototype = default!;

    public event Action<ProtoId<RadioChannelPrototype>, bool>? OnChannelToggled;
    public event Action<ProtoId<RadioChannelPrototype>, bool>? OnSoundToggled;
    public event Action<bool>? OnAllSoundsToggled;

    private bool _allSoundsToggleTarget;

    public HeadsetMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleAllSoundsButton.OnPressed += _ => OnAllSoundsToggled?.Invoke(_allSoundsToggleTarget);
    }

    public void UpdateState(HeadsetBoundUserInterfaceState state)
    {
        ChannelRows.DisposeAllChildren();
        UpdateToggleAllSoundsButton(state);

        if (state.Channels.Count == 0)
        {
            ChannelRows.AddChild(new Label
            {
                Text = Loc.GetString("headset-ui-no-channels"),
                Margin = new Thickness(2, 4),
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        foreach (var channelState in state.Channels
                     .Select(ResolveChannel)
                     .Where(entry => entry != null)
                     .Select(entry => entry!.Value)
                     .OrderBy(entry => Loc.GetString(entry.Prototype.Name)))
        {
            AddChannelRow(channelState);
        }
    }

    private void UpdateToggleAllSoundsButton(HeadsetBoundUserInterfaceState state)
    {
        _allSoundsToggleTarget = state.Channels.Any(channel => !channel.SoundEnabled);
        ToggleAllSoundsButton.Disabled = state.Channels.Count == 0;
        ToggleAllSoundsButton.Text = Loc.GetString(_allSoundsToggleTarget
            ? "headset-ui-enable-all-sounds"
            : "headset-ui-disable-all-sounds");
    }

    private (HeadsetChannelState State, RadioChannelPrototype Prototype)? ResolveChannel(HeadsetChannelState state)
    {
        // Skip channels whose prototypes were removed while a UI state was in flight.
        return _prototype.Resolve(state.Channel, out var prototype)
            ? (state, prototype)
            : null;
    }

    private void AddChannelRow((HeadsetChannelState State, RadioChannelPrototype Prototype) entry)
    {
        var channel = entry.Prototype;
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 2),
        };

        row.AddChild(new Label
        {
            Text = Loc.GetString(channel.Name),
            FontColorOverride = channel.Color,
            HorizontalExpand = true,
            ClipText = true,
            ToolTip = Loc.GetString(channel.Name),
        });

        var channelCheck = MakeCheckBox(
            entry.State.ChannelEnabled,
            Loc.GetString("headset-ui-channel-enabled-tooltip"));
        channelCheck.OnPressed += args => OnChannelToggled?.Invoke(entry.State.Channel, args.Button.Pressed);
        row.AddChild(CenterCheckBox(channelCheck));

        var soundCheck = MakeCheckBox(
            entry.State.SoundEnabled,
            Loc.GetString("headset-ui-sound-enabled-tooltip"));
        soundCheck.OnPressed += args => OnSoundToggled?.Invoke(entry.State.Channel, args.Button.Pressed);
        row.AddChild(CenterCheckBox(soundCheck));

        ChannelRows.AddChild(row);
    }

    private static CheckBox MakeCheckBox(bool pressed, string tooltip)
    {
        return new CheckBox
        {
            Pressed = pressed,
            ToolTip = tooltip,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
    }

    private static Control CenterCheckBox(CheckBox checkBox)
    {
        return new CenterContainer
        {
            MinWidth = CheckColumnWidth,
            Children =
            {
                checkBox,
            },
        };
    }
}
