- type: latheRecipePack
  id: SecurityCaptureDevicePack
  recipes:
  - WeaponGrapplingGunHunter

- type: latheRecipePack
  id: SecurityAmmoStaticCorvaxGoob
  recipes:
  - MagazineLargeCaliber
  - MagazineBoxLargeCaliber

- type: latheRecipePack
  id: NonLethalAmmo
  recipes:
  - MagazineRifleRubber
  - MagazineBoxRifleRubber
  - MagazinePistolRubber
  - MagazinePistolSubMachineGunRubber
  - MagazineBoxPistolRubber
  - MagazineBoxMagnumRubber
  - SpeedLoaderMagnumRubber
  - MagazineShotgunBeanbag
  - BoxBeanbag
  - MagazineBoxShotgunBeanbagHighCaliber