using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.RadialMenu;


[GenerateTypedNameReferences, Virtual]
public sealed partial class RadialButton : Control
{
    [Animatable]
    public Vector2 Offset { get; set; }

    public string? Content { get; set; }

    public string Texture
    {
        set => Controller.TexturePath = value;
    }

    public string? Tooltip
    {
        set => Controller.ToolTip = value;
        get => Controller.ToolTip;
    }

    public new float? TooltipDelay
    {
        set => Controller.TooltipDelay = value;
        get => Controller.TooltipDelay;
    }

    [Animatable]
    public Vector2 ButtonSize
    {
        get => Size;
        set => SetSize = value;
    }

    public RadialButton()
    {
        RobustXamlLoader.Load(this);
        Offset = Vector2.Zero;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
    }
}
