using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Power.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Power.Supermatter.UI;

[GenerateTypedNameReferences]
public sealed partial class SupermatterConsoleWindow : FancyWindow
{
    private const int BarCount = 10;
    private StyleBoxFlat[] _pressureBoxes = null!;
    private StyleBoxFlat[] _temperatureBoxes = null!;

    private static readonly Color ColorSafe = Color.FromHex("#31843E");
    private static readonly Color ColorWarn = Color.FromHex("#A5762F");
    private static readonly Color ColorDanger = Color.FromHex("#BB3232");
    private static readonly Color DimBackgroundColor = Color.FromHex("#333333");
    private static readonly Color ColorInactive = Color.FromHex("#666666");

    public SupermatterConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InitMeters();
    }

    private void InitMeters()
    {
        _pressureBoxes = new StyleBoxFlat[BarCount];
        _temperatureBoxes = new StyleBoxFlat[BarCount];

        for (var i = 0; i < BarCount; i++)
        {
            var pressureBox = new StyleBoxFlat();
            _pressureBoxes[i] = pressureBox;

            PressureMeter.AddChild(new PanelContainer
            {
                Margin = new Thickness(2),
                PanelOverride = pressureBox,
                HorizontalExpand = true,
                VerticalExpand = true,
                MinHeight = 30,
            });

            var tempBox = new StyleBoxFlat();
            _temperatureBoxes[i] = tempBox;

            TemperatureMeter.AddChild(new PanelContainer
            {
                Margin = new Thickness(2),
                PanelOverride = tempBox,
                HorizontalExpand = true,
                VerticalExpand = true,
                MinHeight = 30,
            });
        }
    }

    public void Update(SupermatterConsoleBuiState msg)
    {
        if (msg.Activated)
        {
            TemperatureValue.Text = Loc.GetString("supermatter-console-temp-value", ("value", $"{msg.Temperature:F2}"));
            PressureValue.Text = Loc.GetString("supermatter-console-pressure-value", ("value", $"{msg.Pressure:F2}"));
            IntegrityValue.Text = $"{msg.Integrity:F2}%";
            ActiveEventValue.Text = msg.CurrentEvent;

            TemperatureValue.FontColorOverride = null;
            PressureValue.FontColorOverride = null;
            ActiveEventValue.FontColorOverride = null;
            IntegrityValue.FontColorOverride = msg.IntegrityColor;

            var activePressureBars = CalculateActiveBars(msg.Pressure, msg.PressureThresholds.Item1, msg.PressureThresholds.Item2);
            var activeTempBars = CalculateActiveBars(msg.Temperature, msg.TemperatureThresholds.Item1, msg.TemperatureThresholds.Item2);

            for (var i = 0; i < BarCount; i++)
            {
                var barColor = GetBarColor(i);

                _pressureBoxes[i].BackgroundColor = i < activePressureBars ? barColor : DimBackgroundColor;
                _temperatureBoxes[i].BackgroundColor = i < activeTempBars ? barColor : DimBackgroundColor;
            }

            return;
        }

        TemperatureValue.Text = Loc.GetString("supermatter-console-temp-value", ("value", 0f));
        PressureValue.Text = Loc.GetString("supermatter-console-pressure-value", ("value", 0f));
        IntegrityValue.Text = "—";
        ActiveEventValue.Text = "—";

        TemperatureValue.FontColorOverride = ColorInactive;
        PressureValue.FontColorOverride = ColorInactive;
        ActiveEventValue.FontColorOverride = ColorInactive;
        IntegrityValue.FontColorOverride = ColorInactive;

        foreach (var box in _pressureBoxes)
            box.BackgroundColor = DimBackgroundColor;

        foreach (var box in _temperatureBoxes)
            box.BackgroundColor = DimBackgroundColor;

    }

    private static int CalculateActiveBars(float? value, float? lower, float? upper)
    {
        if (value <= 1f)
            return 1;
        if (value is null || lower is null || upper is null)
            return 0;

        if (value < lower)
        {
            var fraction = value / lower;
            return (int)Math.Round(1f + fraction.Value * 2f);
        }

        if (value <= upper)
        {
            var fraction = (value - lower) / (upper - lower);
            return (int)Math.Round(4f + fraction.Value * 3f);
        }

        var visualMax = upper.Value * 1.5f;
        var overFraction = Math.Clamp((value.Value - upper.Value) / (visualMax - upper.Value), 0f, 1f);

        return (int)Math.Round(8f + overFraction * 2f);
    }

    private static Color GetBarColor(int barIndex)
    {
        return barIndex switch
        {
            < 2 => ColorDanger,
            2 => ColorWarn,
            < 7 => ColorSafe,
            < 9 => ColorWarn,
            _ => ColorDanger,
        };
    }
}
