using Content.Shared.Imperial.Medieval.Administration.Nrp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class ConfirmDialog : DefaultWindow
{
    public NrpMessage Message;
    public ConfirmDialog(NrpMessage message)
    {
        RobustXamlLoader.Load(this);
        Message = message;

        ConfirmButton.OnPressed += _ => Dispose();
        CancelButton.OnPressed += _ => Dispose();
    }

    public void OnConfirmButtonPressed(Action action) =>
        ConfirmButton.OnPressed += _ => action?.Invoke();

}
