using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class ConfirmDialog : DefaultWindow
{
    public ConfirmDialog(Action onConfirm)
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Dispose();
        CancelButton.OnPressed += _ => Dispose();
        ConfirmButton.OnPressed += _ => onConfirm?.Invoke();
    }

}
