using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Content.Shared.IdentityManagement;
using Content.Shared.Imperial.Medieval.Administration.Nrp;

namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpMessageControl : Control
{
    public NrpMessageControl(NrpMessage message)
    {
        RobustXamlLoader.Load(this);

        var info = $"[color=red][{message.Violations}][/color] [color=white]{message.PlayerName}[/color] - [color=white]{message.EntityName}[/color]";
        var job = $", {message.JobName}";

        var infoText = info + (string.IsNullOrEmpty(message.JobName) ? "" : job);

        PlayerInformation.Text = infoText;
        Message.SetMarkup(message.Message);
        AHelp.Command = $"openahelp \"{message.PlayerId}\"";
    }

    public Button ResolveRpButton => ResolveRP;
    public Button ResolveNrpButton => ResolveNRP;

}
