using System.Linq;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpMessageControl : Control
{
    public NrpMessageControl(string playerCKey, NetUserId playerId, string message)
    {
        RobustXamlLoader.Load(this);

        PlayerInformation.Text = $"[color=white]{playerCKey}[/color]";
        Message.SetMarkup(message);
        AHelp.Command = $"openahelp \"{playerId}\"";
    }

    public Button ResolveRpButton => ResolveRP;
    public Button ResolveNrpButton => ResolveNRP;

}
