using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpPanel : DefaultWindow
{
    public NrpPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public Button StatsButton() => AdminStatsButton;
}
