using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpStatsTab : Control
{
    public void PopulateEntries(Dictionary<string, (int, int)> entries)
    {
        Entries.DisposeAllChildren();
        var sortedEntries = entries.OrderByDescending(d => d.Value.Item1);
        foreach (var (administrator, resolves) in sortedEntries)
        {
            var entryControl = new NrpStatsEntry(administrator, resolves.Item1, resolves.Item2);
            Entries.AddChild(entryControl);
        }
    }

    public NrpStatsTab()
    {
        RobustXamlLoader.Load(this);
    }

}
