using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpStatsEntry : Control
{
    public NrpStatsEntry(string administrator, int resolves)
    {
        RobustXamlLoader.Load(this);

        EntryLabel.Text = Loc.GetString("nrp-panel-stats-entry", ("administrator", administrator), ("resolves", resolves));
    }

}
