using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpStatsWindow : DefaultWindow
{
    public void PopulateEntries(Dictionary<string, int> entries)
    {
        Entries.DisposeAllChildren();
        foreach (var (administrator, resolves) in entries)
        {
            var entryControl = new NrpStatsEntry(administrator, resolves);
            Entries.AddChild(entryControl);
        }
    }

    public NrpStatsWindow()
    {
        RobustXamlLoader.Load(this);
    }

}
