using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpStatsWindow : DefaultWindow
{
    public void PopulateEntries(Dictionary<string, int> dbEntries, Dictionary<string, int> roundEntries)
    {
        var entries = new Dictionary<string, (int, int)>();

        var keys = new HashSet<string>(dbEntries.Keys.Concat(roundEntries.Keys));
        foreach (var key in keys)
        {
            dbEntries.TryGetValue(key, out var val1);
            roundEntries.TryGetValue(key, out var val2);
            entries[key] = (val1, val2);
        }

        Entries.DisposeAllChildren();
        var sortedEntries = entries.OrderByDescending(d => d.Value.Item1);
        foreach (var (administrator, resolves) in sortedEntries)
        {
            var entryControl = new NrpStatsEntry(administrator, resolves.Item1, resolves.Item2);
            Entries.AddChild(entryControl);
        }
    }

    public NrpStatsWindow()
    {
        RobustXamlLoader.Load(this);
    }

}
