using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
namespace Content.Client.Imperial.Medieval.Administration.UI.Nrp;

[GenerateTypedNameReferences]
public sealed partial class NrpStatsWindow : DefaultWindow
{
    public void PopulateEntries(Dictionary<string, (int, int)> dbEntries, Dictionary<string, (int, int)> roundEntries)
    {
        GlobalStatsTab.PopulateEntries(dbEntries);
        RoundStatsTab.PopulateEntries(roundEntries);
    }

    public NrpStatsWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("nrp-panel-stats-tab-db"));
        Tabs.SetTabTitle(1, Loc.GetString("nrp-panel-stats-tab-round"));
    }

}
