# Middle

- type: entity
  id: MedievalActionSleepMiddle
  name: medieval-store-spells-multi-currency-sleep-middle-name
  description: medieval-store-spells-multi-currency-sleep-middle-desc
  components:
  - type: CastTraining
    trainingResults:
      - !type:AddMagicEssence
        probability: 1
        addedEssences:
          MagicMedievalLight1: 1
      - !type:AddMagicEssence
        probability: 1
        addedEssences:
          MagicMedievalVodka1: 1
  - type: ManaDrainSpell
    manaDrain: 80
    canUseWithoutMana: false
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 18
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 145
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Imperial/Medieval/sedation_cast.ogg
    icon:
      sprite: Imperial/Medieval/Gun/Charmer/sleep.rsi
      state: 1
  - type: TargetAction
    checkCanAccess: false
    range: 60
  - type: WorldTargetAction
    event: !type:MedievalProjectileSpellEvent
      projectilePrototype:
        0: MedievalProjectileSleepMiddle
      speechPoints:
        0:
          speech: medieval-spell-speach-sleep
          color: "#AC8AA2"
          hideChat: true
  - type: ActionUpgrade
    effectedLevels:
      2: MedievalActionSleepSenior

# Senior

- type: entity
  id: MedievalActionSleepSenior
  parent: MedievalActionSleepMiddle
  name: medieval-store-spells-multi-currency-senior-senior-name
  description: medieval-store-spells-multi-currency-senior-senior-desc
  components:
  - type: ManaDrainSpell
    manaDrain: 80
    canUseWithoutMana: false
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 18
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 130
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Imperial/Medieval/sedation_cast.ogg
    icon:
      sprite: Imperial/Medieval/Gun/Charmer/sleep.rsi
      state: 2
  - type: TargetAction
    checkCanAccess: false
    range: 60
  - type: WorldTargetAction
    event: !type:MedievalProjectileSpellEvent
      projectilePrototype:
        0: MedievalProjectileSleepSenior
      speechPoints:
        0:
          speech: medieval-spell-speach-sleep
          color: "#AC8AA2"
          hideChat: true
