- type: entity
  id: CrateLavaLamps
  parent: CratePlastic
  name: lava lamp crate
  description: Contains 5 lava lamp for your station moth.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomLavaLamp
        rolls: !type:ConstantNumberSelector
          value: 5

- type: entity
  id: CrateGambling
  parent: CrateGenericSteel
  name: gambling crate
  description: A large box containing 3 types of lotteries and a Gamban Law board to attract Borg to gambling.
  components:
  - type: StorageFill
    contents:
      - id: GambamovCircuitBoard
      - id: SlotMachineFlatpack
      - id: CoinFlipperFlatPack
      - id: ClawMachineFlatPack

- type: entity
  id: CrateServiceJanicart
  parent: CratePlastic
  name: janicart crate
  description: Contains a janicart with 3 jugs of space cleaner.
  components:
  - type: StorageFill
    contents:
      - id: VehicleJanicart
      - id: VehicleKeyJanicart
      - id: JugSpaceCleaner
        amount: 3
