// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._CorvaxGoob.CardPdaPainter;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CorvaxGoob.CardPdaPainter;

[GenerateTypedNameReferences]
public sealed partial class CardPdaPainterWindow : DefaultWindow
{
    private readonly List<CardPdaPainterJobEntry> _entries = new();
    private ProtoId<JobPrototype> _selectedJob;
    private bool _hasSelectedJob;

    public event Action? OnTargetSlotPressed;
    public event Action<ProtoId<JobPrototype>>? OnPaintPressed;

    public CardPdaPainterWindow()
    {
        RobustXamlLoader.Load(this);

        TargetSlotButton.OnPressed += _ => OnTargetSlotPressed?.Invoke();
        PaintButton.OnPressed += _ =>
        {
            if (_hasSelectedJob)
                OnPaintPressed?.Invoke(_selectedJob);
        };

        SearchLineEdit.OnTextChanged += _ => RebuildJobList();
    }

    public void UpdateState(CardPdaPainterBoundUserInterfaceState state, IPrototypeManager prototype)
    {
        // The server sends a fresh state after opening the window and after every slot change.
        // This method only redraws labels, the job list, and the preview.
        TargetSlotButton.Text = state.IsTargetPresent
            ? Loc.GetString("card-pda-painter-window-eject")
            : Loc.GetString("card-pda-painter-window-insert");

        TargetNameLabel.Text = state.IsTargetPresent
            ? state.TargetName
            : Loc.GetString("card-pda-painter-window-no-target");

        HintLabel.Text = state.TargetType switch
        {
            CardPdaPainterTargetType.IdCard => Loc.GetString("card-pda-painter-window-hint-id-card"),
            CardPdaPainterTargetType.Pda => Loc.GetString("card-pda-painter-window-hint-pda"),
            _ => Loc.GetString("card-pda-painter-window-hint-empty")
        };

        _entries.Clear();
        _entries.AddRange(state.Jobs);
        _entries.Sort((x, y) =>
        {
            var xName = prototype.TryIndex(x.JobId, out JobPrototype? xJob) ? xJob.LocalizedName : x.JobId.ToString();
            var yName = prototype.TryIndex(y.JobId, out JobPrototype? yJob) ? yJob.LocalizedName : y.JobId.ToString();
            return string.Compare(xName, yName, StringComparison.CurrentCulture);
        });

        // Keep the current selection when possible, but select the first valid entry after target changes.
        if (!_hasSelectedJob || !HasEntry(_selectedJob))
        {
            _hasSelectedJob = _entries.Count > 0;
            if (_hasSelectedJob)
                _selectedJob = _entries[0].JobId;
        }

        RebuildJobList();
        UpdateSelection(prototype);
        PaintButton.Disabled = !_hasSelectedJob;
    }

    private void RebuildJobList()
    {
        JobsContainer.RemoveAllChildren();

        // Searching is purely client-side: the server already sent every valid job style for this target type.
        var prototype = IoCManager.Resolve<IPrototypeManager>();
        var filter = SearchLineEdit.Text.Trim();

        foreach (var entry in _entries)
        {
            if (!prototype.TryIndex(entry.JobId, out JobPrototype? job))
                continue;

            var jobName = job.LocalizedName;
            if (!string.IsNullOrEmpty(filter) &&
                !jobName.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
            {
                continue;
            }

            var button = new Button
            {
                Text = jobName,
                ToggleMode = true,
                Pressed = _hasSelectedJob && _selectedJob == entry.JobId,
                HorizontalExpand = true,
            };

            button.OnPressed += _ =>
            {
                _selectedJob = entry.JobId;
                _hasSelectedJob = true;
                RebuildJobList();
                UpdateSelection(prototype);
            };

            JobsContainer.AddChild(button);
        }
    }

    private void UpdateSelection(IPrototypeManager prototype)
    {
        // The preview uses the exact entity prototype that the server will use as the visual template.
        if (!TryGetSelectedEntry(out var entry) ||
            !prototype.TryIndex(entry.JobId, out JobPrototype? job))
        {
            SelectedJobLabel.Text = Loc.GetString("card-pda-painter-window-no-selection");
            PreviewSprite.SetPrototype(null);
            return;
        }

        SelectedJobLabel.Text = job.LocalizedName;
        PreviewSprite.SetPrototype(entry.VisualPrototype);
    }

    private bool TryGetSelectedEntry(out CardPdaPainterJobEntry selectedEntry)
    {
        selectedEntry = default;

        if (!_hasSelectedJob)
            return false;

        foreach (var entry in _entries)
        {
            if (entry.JobId != _selectedJob)
                continue;

            selectedEntry = entry;
            return true;
        }

        return false;
    }

    private bool HasEntry(ProtoId<JobPrototype> selectedJob)
    {
        foreach (var entry in _entries)
        {
            if (entry.JobId == selectedJob)
                return true;
        }

        return false;
    }
}
