using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.UI.Windows.ChoiceWindow;


[GenerateTypedNameReferences]
public sealed partial class ChoiceWindow : BaseImperialWindow.BaseImperialWindow
{

    public List<ImperialUIWindowChoice> Choices = new();


    private const string ButtonHeaderStyleclass = "ImperialLabelGreyH4";


    public ChoiceWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ReloadChoices();
    }

    #region Helpers

    public void ReloadChoices()
    {
        ChoicesContainer.RemoveAllChildren();

        for (var i = 0; i < Choices.Count; i++)
        {
            var buttonHeaderText = Choices[i].ButtonHeader;
            var buttonTextText = Choices[i].ButtonText;
            var callback = Choices[i].Callback;
            var callbackData = Choices[i].CallbackData;

            var container = new BoxContainer()
            {
                VerticalExpand = true,
                HorizontalExpand = true,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Stretch,
                Margin = i != 0 ? new Thickness(3, 0) : new Thickness(0)
            };

            var buttonHeaderLabel = new Label()
            {
                Text = Loc.GetString(buttonHeaderText),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Top
            };

            var selectionButton = new BaseImperialButton()
            {
                Text = Loc.GetString(buttonTextText),
                VerticalAlignment = VAlignment.Bottom,
                HorizontalAlignment = HAlignment.Stretch,
                HorizontalExpand = true
            };
            selectionButton.OnPressed += (_) => callback(callbackData);

            buttonHeaderLabel.StyleClasses.Add(ButtonHeaderStyleclass);

            container.AddChild(buttonHeaderLabel);
            container.AddChild(selectionButton);

            ChoicesContainer.AddChild(container);
        }
    }

    #endregion
}
