using Content.Client.UserInterface.Controls;
using Content.Shared._CorvaxGoob.ChameleonStamp;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.OptionButton;

namespace Content.Client._CorvaxGoob.ChameleonStamp;

[GenerateTypedNameReferences]
public sealed partial class ChameleonStampWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private EntityUid? _owner;
    private EntityUid? _preview;

    public ChameleonStampWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateVisuals()
    {
        var chameleonSystem = _entMan.System<ChameleonStampSystem>();

        if (!_entMan.TryGetComponent<ChameleonStampComponent>(_owner, out var chameleonStamp))
            return;

        if (!chameleonSystem.ValidatePreset(chameleonStamp.SelectedStampColorPrototype, out var stampColorPrototype, out var stampColorComponent))
            return;

        if (!chameleonSystem.ValidatePreset(chameleonStamp.SelectedStampStatePrototype, out var stampStatePrototype, out var stampStateComponent))
            return;

        if (!chameleonSystem.ValidatePreset(chameleonStamp.SelectedStampSpritePrototype, out var stampSpritePrototype, out var stampSpriteComponent))
            return;

        int i = 0;

        StampColorOptionButton.Clear();
        StampSpriteOptionButton.Clear();
        StampStateOptionButton.Clear();

        foreach (var proto in chameleonSystem.GetAllPresets())
        {
            this.StampColorOptionButton.AddItem(_proto.Index<EntityPrototype>(proto).Name, i);
            StampColorOptionButton.SetItemMetadata(i, proto.Id);
            if (proto == chameleonStamp.SelectedStampColorPrototype)
                StampColorOptionButton.Select(i);

            this.StampSpriteOptionButton.AddItem(_proto.Index<EntityPrototype>(proto).Name, i);
            StampSpriteOptionButton.SetItemMetadata(i, proto.Id);
            if (proto == chameleonStamp.SelectedStampSpritePrototype)
                StampSpriteOptionButton.Select(i);

            this.StampStateOptionButton.AddItem(_proto.Index<EntityPrototype>(proto).Name, i);
            StampStateOptionButton.SetItemMetadata(i, proto.Id);
            if (proto == chameleonStamp.SelectedStampStatePrototype)
                StampStateOptionButton.Select(i);

            i++;
        }

        StampColorOptionButton.OnItemSelected += ColorOptionButton_OnItemSelected;
        StampSpriteOptionButton.OnItemSelected += StampSpriteOptionButton_OnItemSelected;
        StampStateOptionButton.OnItemSelected += StateOptionButton_OnItemSelected;

        _preview = _entMan.Spawn(chameleonStamp.SelectedStampSpritePrototype, MapCoordinates.Nullspace);

        this.StampMetaDataName.PlaceHolder = Loc.GetString(stampSpritePrototype.Name);
        this.StampMetaDataDescription.PlaceHolder = Loc.GetString(stampSpritePrototype.Description);

        this.StampMetaDataName.Text = Loc.GetString(chameleonStamp.CustomName ?? "");
        this.StampMetaDataDescription.Text = Loc.GetString(chameleonStamp.CustomDescription ?? "");
        this.StampedNameLineEdit.Text = Loc.GetString(chameleonStamp.StampedName ?? "");

        StampColorSelector.Color = chameleonStamp.CustomStampColor.HasValue ? chameleonStamp.CustomStampColor.Value : stampColorComponent.StampedColor;

        this.StampedNameLineEdit.PlaceHolder = Loc.GetString(stampSpriteComponent.StampedName);
        SpritePreview.SetEntity(_preview);
    }

    private void StateOptionButton_OnItemSelected(ItemSelectedEventArgs obj)
    {
        var meta = StampStateOptionButton.GetItemMetadata(obj.Id);
        if (meta is null)
            return;

        if (!_proto.Index<EntityPrototype>((string) meta).TryGetComponent<SpriteComponent>(out var presetSprite))
            return;

        StampStateOptionButton.Select(obj.Id);
    }

    private void StampSpriteOptionButton_OnItemSelected(ItemSelectedEventArgs obj)
    {
        var meta = StampSpriteOptionButton.GetItemMetadata(obj.Id);
        if (meta is null)
            return;

        if (!_proto.Index<EntityPrototype>((string) meta).TryGetComponent<SpriteComponent>(out var presetSprite))
            return;

        if (!_entMan.TryGetComponent<SpriteComponent>(_preview, out var previewSprite))
            return;

        previewSprite.CopyFrom(presetSprite);
        StampSpriteOptionButton.Select(obj.Id);
    }

    private void ColorOptionButton_OnItemSelected(ItemSelectedEventArgs obj)
    {
        var meta = StampColorOptionButton.GetItemMetadata(obj.Id);
        if (meta is null)
            return;

        if (!_proto.Index<EntityPrototype>((string) meta).TryGetComponent<StampComponent>(out var stamp))
            return;

        StampColorSelector.Color = stamp.StampedColor;
        StampColorOptionButton.Select(obj.Id);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        UpdateVisuals();
    }
}
