using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.UI.Windows.ImperialInfoWindow;


[GenerateTypedNameReferences]
public sealed partial class ImperialInfoWindow : BaseImperialWindow.BaseImperialWindow
{
    public event Action? OnSubmitButtonPressed;


    [ViewVariables]
    public string? HeaderInfoText { get => HeaderLabelText.Text; set => HeaderLabelText.Text = value; }

    [ViewVariables]
    public string? InfoPanelText { get => InfoText.Text; set => InfoText.Text = value; }

    [ViewVariables]
    public string? SubmitButtonLabelText { get => SubmitButtonText.Text; set => SubmitButtonText.Text = value; }


    public ImperialInfoWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SubmitButton.OnPressed += (_) => OnSubmitButtonPressed?.Invoke();
    }
}
