using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Imperial.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    public event Action? OnNotificationSwitchPressed;
    public event Action<string>? OnSendMessage;
    public event Action<int>? OnChatSelected;
    public event Action<string>? OnCreateChat;
    public event Action? OnTypingMessage;
    public event Action? OnSendLocation;
    public event Action<int, List<NetEntity>>? OnAddMembers;
    public event Action<int, List<NetEntity>>? OnRemoveMembers;
    public event Action<int, string>? OnEditChat;
    public event Action? OnPrint;

    public enum NanoChatMode
    {
        Contacts,
        GroupChats,
        AddingMembers,
        EditingChat,
    }

    private NetEntity? _userId;

    private readonly TimeSpan _cooldown = TimeSpan.FromSeconds(5);
    private TimeSpan _lastTyping;
    private TimeSpan _lastPrint;
    private TimeSpan _typingIndicatorTimeout;

    private readonly HashSet<NetEntity> _selectedMembers = new();
    private NanoChatBoundUserInterfaceState? _lastState;
    private Button? _selectedChat;

    private string _searchQuery = string.Empty;

    private NanoChatMode _currentMode = NanoChatMode.Contacts;

    private readonly Dictionary<NanoChatMode, LocId> _sidebarOptions = new()
    {
        { NanoChatMode.Contacts, "nano-chat-ui-menu-options-contacts" },
        { NanoChatMode.GroupChats, "nano-chat-ui-menu-options-group-chats" },
    };

    [Dependency] private readonly IEntitySystemManager _entitySystemManager = null!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = null!;
    [Dependency] private readonly IGameTiming _gameTiming = null!;
    private readonly SpriteSystem _spriteSystem;

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystemManager.GetEntitySystem<SpriteSystem>();

        foreach (var (id, name) in _sidebarOptions)
            OptionsMenu.AddItem(Loc.GetString(name), (int)id);

        OptionsMenu.OnItemSelected += args =>
        {
            OptionsMenu.SelectId(args.Id);
            _currentMode = (NanoChatMode)args.Id;

            if (_lastState != null)
                UpdateState(_lastState);
        };

        MenuButton.OnPressed += _ =>
        {
            MenuPanel.Visible = !MenuPanel.Visible;
        };

        NewChatNameInput.OnTextChanged += _ =>
        {
            if (string.IsNullOrWhiteSpace(NewChatNameInput.Text))
            {
                NewChatButton.Disabled = true;
                return;
            }

            NewChatButton.Disabled = false;
        };

        NewChatButton.OnPressed += _ =>
        {
            OnCreateChat?.Invoke(NewChatNameInput.Text);
            NewChatNameInput.Text = string.Empty;
            NewChatButton.Disabled = true;
            MenuPanel.Visible = false;
            MenuButton.Pressed = false;
        };

        SearchInput.OnTextChanged += args =>
        {
            _searchQuery = args.Text;
            if (_lastState != null)
                UpdateState(_lastState);
        };

        NotificationSwitch.OnPressed += _ => OnNotificationSwitchPressed?.Invoke();

        MessageTextInput.OnTextChanged += OnTextInputTextChanged;

        SendLocationButton.OnPressed += _ => OnSendLocation?.Invoke();

        PrintChatButton.OnPressed += _ => OnPrintButtonPressed();

        SendButton.OnPressed += _ => SendMessage();
        MessageTextInput.OnTextEntered += _ => SendMessage();

        AddMembersButton.OnPressed += _ => OnAddMembersButtonPressed();

        EditChatNameInput.OnTextEntered += _ => OnEditChatButtonPressed();
        EditChatButton.OnPressed += _ => OnEditChatButtonPressed();
    }

    /// <summary>
    /// Обновление состояния UI.
    /// </summary>
    public void UpdateState(NanoChatBoundUserInterfaceState state)
    {
        _lastState = state;
        _userId = state.CurrentUserId;

        ContactsListContainer.DisposeAllChildren();
        MessageContainer.DisposeAllChildren();

        UpdateCurrentChatDisplay(state.CurrentChat, state.IsServerOnline, state.Contacts);

        AddMembersButton.Visible = state.CurrentChat != null;
        SendLocationButton.Visible = state.CanSendLocation;
        EditChatButton.Visible = state.CurrentChat?.Owner == _userId ;
        CreateChatContainer.Visible = OptionsMenu.SelectedId == (int)NanoChatMode.GroupChats;
        SearchContainer.Visible = OptionsMenu.SelectedId == (int) NanoChatMode.Contacts;

        AddMembersButton.Pressed = _currentMode == NanoChatMode.AddingMembers;
        EditChatButton.Pressed = _currentMode == NanoChatMode.EditingChat;
        EditChatNameInput.Visible = EditChatButton.Pressed;
        CurrentContactLabel.Visible = !EditChatButton.Pressed;

        var canSend = state is { IsServerOnline: true, CurrentChat: not null, IsContactReachable: true };
        SendButton.Disabled = !canSend;
        SendLocationButton.Disabled = !canSend;

        var isPrintOnCooldown = _gameTiming.CurTime - _lastPrint <= _cooldown;
        PrintChatButton.Disabled = !canSend || !state.CanPrint || isPrintOnCooldown;

        NotificationSwitch.Text = Loc.GetString(
            state.NotificationOn
                ? "news-read-ui-notification-on"
                : "news-read-ui-notification-off");


        var sortedChats = state.Chats.OrderByDescending(c =>
            state.UnreadMessages.TryGetValue(c.Id, out var chatUnreadCount) && chatUnreadCount > 0);

        var allUnreadCount = state.UnreadMessages.Values.Sum();
        MenuButton.Text = allUnreadCount > 0
            ? Loc.GetString("nano-chat-ui-menu-open-button-unread", ("unread", allUnreadCount))
            : Loc.GetString("nano-chat-ui-menu-open-button");

        var filteredChats = _currentMode switch
        {
            NanoChatMode.Contacts => sortedChats.Where(c =>
                (state.UnreadMessages.TryGetValue(c.Id, out var unread) && unread > 0) ||
                (c.Automated && MatchesSearch(c, state.Contacts, _searchQuery))),
            NanoChatMode.GroupChats => sortedChats.Where(c => !c.Automated),
            _ => sortedChats,
        };

        if (state is { CurrentChat: not null, TypingUsers.Count: > 0 })
        {
            var typingNames = string.Join(", ", state.TypingUsers.Values);

            TypingIndicatorLabel.Text = Loc.GetString("nano-chat-ui-typing-indicator",
                ("names", typingNames),
                ("count", state.TypingUsers.Count));

            TypingIndicatorLabel.Visible = true;
            _typingIndicatorTimeout = _gameTiming.CurTime + _cooldown;
        }
        else
            TypingIndicatorLabel.Visible = false;

        foreach (var chat in filteredChats)
            AddAContact(chat, state);

        HandleNanoChatMode(state);
    }


    /// <summary>
    /// Отправляет сообщение о печатании в текущем чате.
    /// </summary>
    private void OnTextInputTextChanged(LineEdit.LineEditEventArgs args)
    {
        var curTime = _gameTiming.CurTime;
        if (curTime - _lastTyping <= _cooldown)
            return;

        _lastTyping = curTime;
        OnTypingMessage?.Invoke();
    }

    /// <summary>
    /// Отправляет сообщение о печати истории чата.
    /// </summary>
    private void OnPrintButtonPressed()
    {
        var curTime = _gameTiming.CurTime;
        if (curTime - _lastPrint <= _cooldown)
            return;

        _lastPrint = curTime;
        PrintChatButton.Disabled = true;
        OnPrint?.Invoke();
    }

    /// <summary>
    /// Отправляет сообщение в текущий чат.
    /// </summary>
    private void SendMessage(string? message = null)
    {
        var text = message ?? MessageTextInput.Text;
        if (SendButton.Disabled || string.IsNullOrWhiteSpace(text))
            return;

        ChatScroll.SetScrollValue(new Vector2(0f, float.MaxValue));

        OnSendMessage?.Invoke(text);
        if (message is null)
            MessageTextInput.Text = string.Empty;
    }

    /// <summary>
    /// Установка режима добавления пользователей в чат, отправка сообщений о добавлении пользователей.
    /// </summary>
    private void OnAddMembersButtonPressed()
    {
        if (_lastState?.CurrentChat == null)
            return;

        if (_currentMode != NanoChatMode.AddingMembers)
            _currentMode = NanoChatMode.AddingMembers;
        else
        {
            if (_selectedMembers.Count > 0)
                OnAddMembers?.Invoke(_lastState.CurrentChat.Id, _selectedMembers.ToList());

            _currentMode = NanoChatMode.GroupChats;
        }

        _selectedMembers.Clear();

        if (_lastState != null)
            UpdateState(_lastState);
    }

    /// <summary>
    /// Установка режима изменения чата, отправка сообщений об изменении чата.
    /// </summary>
    private void OnEditChatButtonPressed()
    {
        if (_lastState?.CurrentChat == null)
            return;

        if (_currentMode != NanoChatMode.EditingChat)
        {
            _currentMode = NanoChatMode.EditingChat;
            EditChatNameInput.Text = _lastState.CurrentChat.Name;
        }
        else
        {
            if (EditChatNameInput.Text != _lastState.CurrentChat.Name
                && !string.IsNullOrWhiteSpace(EditChatNameInput.Text))
            {
                OnEditChat?.Invoke(_lastState.CurrentChat.Id, EditChatNameInput.Text);
                CurrentContactLabel.Text = EditChatNameInput.Text;
            }

            if (_selectedMembers.Count > 0)
                OnRemoveMembers?.Invoke(_lastState.CurrentChat.Id, _selectedMembers.ToList());

            _currentMode = _lastState.CurrentChat.Automated ? NanoChatMode.Contacts : NanoChatMode.GroupChats;
        }

        if (_lastState != null)
            UpdateState(_lastState);
    }


    /// <summary>
    /// Обновление имени чата и его состояния.
    /// </summary>
    private void UpdateCurrentChatDisplay(NanoChatChat? chat, bool isServerOnline, List<NanoChatContact> contacts)
    {
        if (!isServerOnline)
        {
            CurrentContactIcon.Visible = false;
            CurrentContactLabel.Text = Loc.GetString("nano-chat-ui-chat-window-no-chat-selected");

            var noServerLabel = new Label()
            {
                Text = Loc.GetString("nano-chat-ui-chat-window-message-server-unreachable"),
                Align = Label.AlignMode.Center,
                FontColorOverride = Color.Red,
            };
            MessageContainer.AddChild(noServerLabel);
            return;
        }
        if (chat is null)
        {
            CurrentContactIcon.Visible = false;
            CurrentContactLabel.Text = Loc.GetString("nano-chat-ui-chat-window-no-chat-selected");
            return;
        }

        NanoChatContact? singleContact = null;
        if (chat.Automated && _userId != null)
        {
            var otherId = chat.Members.FirstOrDefault(m => m != _userId.Value);
            foreach (var c in contacts.Where(c => c.Id == otherId))
            {
                singleContact = c;
                break;
            }
        }


        if (singleContact is null)
        {
            CurrentContactLabel.Text = chat.Name;
            CurrentContactIcon.Visible = false;
            return;
        }

        CurrentContactLabel.Text = Loc.GetString("nano-chat-ui-chat-window-contact-name-job",
            ("name", singleContact.Value.Name),
            ("job", GetJobTitle(singleContact.Value.JobTitle)));

        if (singleContact.Value.JobIconId != null
            && _prototypeManager.TryIndex(singleContact.Value.JobIconId, out var jobIconProto))
        {
            CurrentContactIcon.Texture = _spriteSystem.Frame0(jobIconProto.Icon);
            CurrentContactIcon.Visible = true;
        }
        else
            CurrentContactIcon.Visible = false;
    }

    /// <summary>
    /// Проверка контакта на соответствие запросу.
    /// </summary>
    private bool MatchesSearch(NanoChatChat chat, List<NanoChatContact> contacts, string query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return true;

        if (!string.IsNullOrEmpty(chat.Name) && chat.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        if (chat.Members.Count > 2 || _userId == null)
            return false;

        if (!chat.Members.Contains(_userId.Value))
        {
            var member1 = contacts.FirstOrDefault(c => c.Id == chat.Members.ElementAtOrDefault(0));
            var member2 = contacts.FirstOrDefault(c => c.Id == chat.Members.ElementAtOrDefault(1));

            return (member1.Name?.Contains(query, StringComparison.OrdinalIgnoreCase) == true) ||
                   (GetJobTitle(member1.JobTitle).Contains(query, StringComparison.OrdinalIgnoreCase)) ||
                   (member2.Name?.Contains(query, StringComparison.OrdinalIgnoreCase) == true) ||
                   (GetJobTitle(member2.JobTitle).Contains(query, StringComparison.OrdinalIgnoreCase)) ||
                   chat.Id.ToString().Contains(query);
        }

        var otherId = chat.Members.FirstOrDefault(m => m != _userId.Value);
        var contact = contacts.FirstOrDefault(c => c.Id == otherId);

        if (contact.Name != null && contact.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        var jobTitle = GetJobTitle(contact.JobTitle);


        return jobTitle.Contains(query, StringComparison.OrdinalIgnoreCase); // || chat.Messages.Any(m => m.Content.Contains(query));
    }

    /// <summary>
    /// Добавляет контакт в левую панель.
    /// </summary>
    private void AddAContact(NanoChatChat chat, NanoChatBoundUserInterfaceState state)
    {
        var isCurrentChat = state.CurrentChat?.Id == chat.Id;

        var btn = new Button
        {
            Margin = new Thickness(0, 0, 0, 2),
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = isCurrentChat,
        };

        if (isCurrentChat)
            _selectedChat = btn;

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        NanoChatContact? singleContact = null;
        NanoChatContact? adminContact1 = null;
        NanoChatContact? adminContact2 = null;

        if (chat.Automated && _userId != null)
        {
            if (state.FinePrintText && chat.Members.Count >= 2)
            {
                adminContact1 = state.Contacts.FirstOrDefault(c => c.Id == chat.Members[0]);
                adminContact2 = state.Contacts.FirstOrDefault(c => c.Id == chat.Members[1]);
            }
            else
            {
                var otherId = chat.Members.FirstOrDefault(m => m != _userId.Value);
                singleContact = state.Contacts.FirstOrDefault(c => c.Id == otherId);
            }
        }

        string text;
        if (state.FinePrintText && adminContact1 != null && adminContact2 != null)
        {
            text = Loc.GetString("nano-chat-ui-contacts-contact-name-job-fine",
                ("name1", adminContact1.Value.Name ?? Loc.GetString("nano-chat-ui-chat-window-sender-unknown")),
                ("job1", GetJobTitle(adminContact1.Value.JobTitle)),
                ("name2", adminContact2.Value.Name ?? Loc.GetString("nano-chat-ui-chat-window-sender-unknown")),
                ("job2", GetJobTitle(adminContact2.Value.JobTitle)));
        }
        else if (singleContact is not null)
        {
            if (singleContact.Value.JobIconId != null && _prototypeManager.TryIndex(singleContact.Value.JobIconId, out var jobIconProto))
            {
                var icon = new TextureRect
                {
                    Texture = _spriteSystem.Frame0(jobIconProto.Icon),
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(0, 0, 4, 0),
                };
                row.AddChild(icon);
            }
            text = Loc.GetString("nano-chat-ui-contacts-contact-name-job",
                ("name", singleContact.Value.Name ?? Loc.GetString("nano-chat-ui-chat-window-sender-unknown")),
                ("job", GetJobTitle(singleContact.Value.JobTitle)));
        }
        else
            text = chat.Name;

        if (!state.FinePrintText && state.UnreadMessages.TryGetValue(chat.Id, out var unreadCount) && unreadCount > 0)
        {
            text = Loc.GetString("nano-chat-ui-contacts-contact-name-job-unread",
                ("name-job", text),
                ("unread", unreadCount));
        }

        var label = new RichTextLabel() { Text = text, HorizontalExpand = true };
        row.AddChild(label);
        btn.AddChild(row);

        btn.OnPressed += _ => SelectChat(btn, chat, state);
        ContactsListContainer.AddChild(btn);
    }

    /// <summary>
    /// Обработка всех возможных состояний действий.
    /// </summary>
    private void HandleNanoChatMode(NanoChatBoundUserInterfaceState state)
    {
        switch (_currentMode)
        {
            case NanoChatMode.EditingChat:
            case NanoChatMode.AddingMembers:
            {
                if (state.CurrentChat == null)
                    return;

                var hasAvailableContacts = state.Contacts.Exists(contact =>
                    contact.Id != _userId &&
                    (_currentMode == NanoChatMode.AddingMembers
                        ? !state.CurrentChat.Members.Contains(contact.Id)
                        : state.CurrentChat.Members.Contains(contact.Id)));

                if (!hasAvailableContacts)
                {
                    MessageContainer.AddChild(new Label { Text = Loc.GetString("nano-chat-ui-chat-window-no-available-contacts") });
                    break;
                }

                var instruction = new Label { Text = Loc.GetString("nano-chat-ui-chat-window-add-contacts") };

                if (_currentMode is NanoChatMode.EditingChat)
                    instruction.Text = Loc.GetString("nano-chat-ui-chat-window-editing-contacts");

                MessageContainer.AddChild(instruction);

                var relevantContacts = state.Contacts.Where(contact =>
                    contact.Id != _userId &&
                    (_currentMode == NanoChatMode.AddingMembers
                        ? !state.CurrentChat.Members.Contains(contact.Id)
                        : state.CurrentChat.Members.Contains(contact.Id)));

                foreach (var contact in relevantContacts)
                {
                    var btnText = Loc.GetString(
                        "nano-chat-ui-chat-window-contact-name-job",
                        ("name", contact.Name),
                        ("job", GetJobTitle(contact.JobTitle)));

                    var btn = new Button
                    {
                        Text = btnText,
                        TextAlign = Label.AlignMode.Left,
                        ToggleMode = true,
                        Pressed = _selectedMembers.Contains(contact.Id),
                    };

                    btn.OnPressed += _ =>
                    {
                        if (!_selectedMembers.Remove(contact.Id))
                            _selectedMembers.Add(contact.Id);

                        if (_lastState != null)
                            UpdateState(_lastState);
                    };

                    MessageContainer.AddChild(btn);
                }
                break;
            }
            default:
            case NanoChatMode.Contacts:
            case NanoChatMode.GroupChats:
                if (state.CurrentChat?.Messages == null)
                    return;

                foreach (var msg in state.CurrentChat.Messages)
                    AddMessageBubble(msg);
                break;
        }
    }

    /// <summary>
    /// Добавляет облачко текста в окно с сообщениями.
    /// </summary>
    private void AddMessageBubble(NanoChatMessage msg)
    {
        var displaySender = msg.SenderName;

        if (msg.SenderId == _userId)
            displaySender = Loc.GetString("nano-chat-ui-chat-window-sender-you");
        else if (string.IsNullOrEmpty(displaySender))
            displaySender = Loc.GetString("nano-chat-ui-chat-window-sender-unknown");

        var wrapper = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var panel = new PanelContainer
        {
            StyleClasses = { StyleClass.BackgroundPanelDark },
            HorizontalExpand = false,
            MouseFilter = MouseFilterMode.Pass,
            ToolTip = Loc.GetString("nano-chat-ui-chat-window-message-tooltip", ("time", msg.SendTime.ToString(@"hh\:mm\:ss"))),
        };

        if (msg.SenderId == _userId)
        {
            wrapper.AddChild(new Control { HorizontalExpand = true });
            wrapper.AddChild(panel);
        }
        else
        {
            wrapper.AddChild(panel);
            wrapper.AddChild(new Control { HorizontalExpand = true });
        }

        var label = new RichTextLabel();
        label.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("nano-chat-ui-chat-window-message",
                ("sender", displaySender),
                ("content", msg.Content))));

        panel.AddChild(label);
        MessageContainer.AddChild(wrapper);
    }

    /// <summary>
    /// Выбирает чат в интерфейсе.
    /// </summary>
    private void SelectChat(Button btn, NanoChatChat chat, NanoChatBoundUserInterfaceState state)
    {
        if (state.CurrentChat?.Id == chat.Id)
        {
            btn.Pressed = true;
            return;
        }

        _selectedChat?.Pressed = false;
        _selectedChat = btn;
        _selectedChat.Pressed = true;

        MenuPanel.Visible = false;
        MenuButton.Pressed = false;
        AddMembersButton.Pressed = false;

        _currentMode = chat.Automated ? NanoChatMode.Contacts : NanoChatMode.GroupChats;
        OptionsMenu.SelectId((int)_currentMode);
        _selectedMembers.Clear();

        UpdateCurrentChatDisplay(chat, true, state.Contacts);

        MessageContainer.DisposeAllChildren();
        MessageContainer.AddChild(new RichTextLabel
        {
            Margin = new Thickness(0, 0, 0, 5),
            Text = Loc.GetString("nano-chat-ui-chat-window-message-loading"),
        });

        OnChatSelected?.Invoke(chat.Id);
    }

    /// <param name="jobTitle">Имя профессии</param>
    /// <returns>Или имя профессии, или Неизвестный, если оно 'nano-chat-ui-contact-job-unknown'</returns>
    private static string GetJobTitle(string? jobTitle)
    {
        return jobTitle is null or "nano-chat-ui-contact-job-unknown"
            ? Loc.GetString("nano-chat-ui-contact-job-unknown")
            : jobTitle;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (TypingIndicatorLabel.Visible && _gameTiming.CurTime > _typingIndicatorTimeout)
            TypingIndicatorLabel.Visible = false;

        var isPrintOnCooldown = _gameTiming.CurTime - _lastPrint <= _cooldown;

        if (!PrintChatButton.Disabled && isPrintOnCooldown)
            PrintChatButton.Disabled = true;
        else if (!isPrintOnCooldown)
            PrintChatButton.Disabled = false;
    }
}
