using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Imperial.CartridgeLoader.Cartridges;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    public event Action? OnNotificationSwitchPressed;
    public event Action<string>? OnSendMessage;
    public event Action<int>? OnChatSelected;
    public event Action<string>? OnCreateChat;
    public event Action? OnTypingMessage;
    public event Action? OnSendLocation;

    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypeManager;
    private readonly IGameTiming _gameTiming;

    private NetEntity? _myId;
    private readonly TimeSpan _typingCooldown = TimeSpan.FromSeconds(5);
    private TimeSpan _lastTyping;

    public event Action<int, List<NetEntity>>? OnAddMembers;

    private bool _isSelectingContacts;
    private readonly HashSet<NetEntity> _selectedNewMembers = new();
    private NanoChatBoundUserInterfaceState? _lastState;
    private Button? _selectedChat;

    private int _currentMenuMode;
    private string _searchQuery = string.Empty;

    private readonly Dictionary<int, LocId> _options = new()
    {
        { 0, "nano-chat-ui-menu-options-contacts" },
        { 1, "nano-chat-ui-menu-options-group-chats" },
    };

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);

        var entSysMan = IoCManager.Resolve<IEntitySystemManager>();
        _spriteSystem = entSysMan.GetEntitySystem<SpriteSystem>();
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        _gameTiming = IoCManager.Resolve<IGameTiming>();

        foreach (var (id, name) in _options)
            OptionsMenu.AddItem(Loc.GetString(name), id);

        OptionsMenu.OnItemSelected += args =>
        {
            OptionsMenu.SelectId(args.Id);
            _currentMenuMode = args.Id;

            if (_lastState != null)
                UpdateState(_lastState);
        };

        MenuButton.OnPressed += _ =>
        {
            ContactsPanel.Visible = !ContactsPanel.Visible;
        };

        NewChatNameInput.OnTextChanged += _ =>
        {
            if (string.IsNullOrWhiteSpace(NewChatNameInput.Text))
            {
                NewChatButton.Disabled = true;
                return;
            }

            NewChatButton.Disabled = false;
        };

        NewChatButton.OnPressed += _ =>
        {
            OnCreateChat?.Invoke(NewChatNameInput.Text);
            NewChatNameInput.Text = string.Empty;
            NewChatButton.Disabled = true;
        };

        SearchInput.OnTextChanged += args =>
        {
            _searchQuery = args.Text;
            if (_lastState != null)
                UpdateState(_lastState);
        };

        NotificationSwitch.OnPressed += _ => OnNotificationSwitchPressed?.Invoke();

        TextInput.OnTextChanged += OnTextInputTextChanged;

        SendLocationButton.OnPressed += _ => OnSendLocation?.Invoke();

        SendButton.OnPressed += _ => SendMessage();
        TextInput.OnTextEntered += _ => SendMessage();

        AddMembersButton.OnPressed += _ =>
        {
            if (_lastState?.CurrentChat == null)
                return;

            if (!_isSelectingContacts)
            {
                _isSelectingContacts = true;
                _selectedNewMembers.Clear();
                AddMembersButton.Pressed = true;
            }
            else
            {
                if (_selectedNewMembers.Count > 0)
                    OnAddMembers?.Invoke(_lastState.CurrentChat.Id, _selectedNewMembers.ToList());
                _isSelectingContacts = false;
                _selectedNewMembers.Clear();

                AddMembersButton.Pressed = false;
            }

            if (_lastState != null)
                UpdateState(_lastState);
        };
    }

    private void OnTextInputTextChanged(LineEdit.LineEditEventArgs args)
    {
        var curTime = _gameTiming.CurTime;
        if (curTime - _lastTyping <= _typingCooldown)
            return;

        _lastTyping = curTime;
        OnTypingMessage?.Invoke();
    }

    private static string GetJobTitle(string? jobTitle)
    {
        return jobTitle is null or "nano-chat-ui-contact-job-unknown"
            ? Loc.GetString("nano-chat-ui-contact-job-unknown")
            : jobTitle;
    }

    private void SendMessage(string? message = null)
    {
        var text = message ?? TextInput.Text;
        if (SendButton.Disabled || string.IsNullOrWhiteSpace(text))
            return;

        ChatScroll.SetScrollValue(new Vector2(0f, float.MaxValue));

        OnSendMessage?.Invoke(text);
        if (message is null)
            TextInput.Text = string.Empty;
    }

    private void UpdateCurrentChatDisplay(NanoChatChat? chat, bool isServerOnline, List<NanoChatContact> contacts)
    {
        if (!isServerOnline || chat == null)
        {
            CurrentContactIcon.Visible = false;
            CurrentContactLabel.Text = Loc.GetString("nano-chat-ui-chat-window-no-chat-selected");
            return;
        }

        NanoChatContact? singleContact = null;

        if (string.IsNullOrEmpty(chat.Name))
        {
            if (chat.Members.Count == 2 && _myId != null)
            {
                var otherId = chat.Members.FirstOrDefault(m => m != _myId.Value);
                foreach (var c in contacts.Where(c => c.Id == otherId))
                {
                    singleContact = c;
                    break;
                }
            }
        }

        if (singleContact != null)
        {
            CurrentContactLabel.Text = Loc.GetString(
                "nano-chat-ui-chat-window-contact-name-job",
                ("name", singleContact.Value.Name),
                ("job", GetJobTitle(singleContact.Value.JobTitle)));

            if (singleContact.Value.JobIconId != null
                && _prototypeManager.TryIndex<JobIconPrototype>(singleContact.Value.JobIconId, out var jobIconProto))
            {
                CurrentContactIcon.Texture = _spriteSystem.Frame0(jobIconProto.Icon);
                CurrentContactIcon.Visible = true;
            }
            else
                CurrentContactIcon.Visible = false;
        }
        else
        {
            CurrentContactLabel.Text = chat.Name;
            CurrentContactIcon.Visible = false;
        }
    }

    private bool MatchesSearch(NanoChatChat chat, List<NanoChatContact> contacts, string query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return true;

        if (!string.IsNullOrEmpty(chat.Name) && chat.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        if (chat.Members.Count > 2 || _myId == null)
            return false;

        var otherId = chat.Members.FirstOrDefault(m => m != _myId.Value);
        var contact = contacts.FirstOrDefault(c => c.Id == otherId);

        if (contact.Name != null && contact.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        var jobTitle = GetJobTitle(contact.JobTitle);

        return jobTitle.Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    public void UpdateState(NanoChatBoundUserInterfaceState state)
    {
        _lastState = state;
        _myId = state.CurrentUserId;

        NotificationSwitch.Text = Loc.GetString(
            state.NotificationOn
                ? "news-read-ui-notification-on"
                : "news-read-ui-notification-off");

        UpdateCurrentChatDisplay(state.CurrentChat, state.IsServerOnline, state.Contacts);

        var canSend = state is { IsServerOnline: true, CurrentChat: not null, IsContactReachable: true };
        SendButton.Disabled = !canSend;
        SendLocationButton.Disabled = !canSend;

        ContactsListContainer.DisposeAllChildren();
        MessageContainer.DisposeAllChildren();

        AddMembersButton.Visible = state.CurrentChat != null;
        SendLocationButton.Visible = state.CanSendLocation;

        if (!state.IsServerOnline)
        {
            var noServerLabel = new Label()
            {
                Text = Loc.GetString("nano-chat-ui-chat-window-message-server-unreachable"),
                Align = Label.AlignMode.Center,
            };
            MessageContainer.AddChild(noServerLabel);
            return;
        }

        CreateChatContainer.Visible = _currentMenuMode == 1;
        SearchContainer.Visible = _currentMenuMode == 0;

        var sortedChats = state.Chats.OrderByDescending(c =>
            state.UnreadMessages.TryGetValue(c.Id, out var unreadCount) && unreadCount > 0);

        var allUnreadCount = state.UnreadMessages.Values.Sum();
        MenuButton.Text = allUnreadCount > 0
            ? Loc.GetString("nano-chat-ui-menu-open-button-unread", ("unread", allUnreadCount))
            : Loc.GetString("nano-chat-ui-menu-open-button");

        var filteredChats = _currentMenuMode switch
        {
            0 => sortedChats.Where(c =>
                (state.UnreadMessages.TryGetValue(c.Id, out var unread) && unread > 0) ||
                (c.Automated && MatchesSearch(c, state.Contacts, _searchQuery))),
            1 => sortedChats.Where(c => !c.Automated),
            _ => sortedChats,
        };

        foreach (var chat in filteredChats)
        {
            var isCurrentChat = state.CurrentChat?.Id == chat.Id;

            var btn = new Button
            {
                Margin = new Thickness(0, 0, 0, 2),
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = isCurrentChat,
            };

            if (isCurrentChat)
                _selectedChat = btn;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            NanoChatContact? singleContact = null;

            if (string.IsNullOrEmpty(chat.Name))
            {
                if (chat.Members.Count == 2 && _myId != null)
                {
                    var otherId = chat.Members.FirstOrDefault(m => m != _myId.Value);
                    foreach (var c in state.Contacts.Where(c => c.Id == otherId))
                    {
                        singleContact = c;
                        break;
                    }
                }
            }

            string text;
            if (singleContact != null)
            {
                if (singleContact.Value.JobIconId != null && _prototypeManager.TryIndex<JobIconPrototype>(singleContact.Value.JobIconId, out var jobIconProto))
                {
                    var icon = new TextureRect
                    {
                        Texture = _spriteSystem.Frame0(jobIconProto.Icon),
                        TextureScale = new Vector2(2, 2),
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(0, 0, 4, 0),
                    };
                    row.AddChild(icon);
                }
                text = Loc.GetString(
                    "nano-chat-ui-contacts-contact-name-job",
                    ("name", singleContact.Value.Name),
                    ("job", GetJobTitle(singleContact.Value.JobTitle)));
            }
            else
                text = chat.Name;

            if (state.UnreadMessages.TryGetValue(chat.Id, out var unreadCount) && unreadCount > 0)
            {
                text = Loc.GetString("nano-chat-ui-contacts-contact-name-job-unread",
                    ("name-job", text),
                    ("unread", unreadCount));
            }

            var label = new RichTextLabel() { Text = text, HorizontalExpand = true, VerticalAlignment = VAlignment.Center };
            row.AddChild(label);
            btn.AddChild(row);

            btn.OnPressed += _ =>
            {
                if (state.CurrentChat?.Id == chat.Id)
                {
                    btn.Pressed = true;
                    return;
                }

                if (chat.Members.Count > 2 && _currentMenuMode != 1)
                {
                    _currentMenuMode = 1;
                    OptionsMenu.SelectId(_currentMenuMode);

                    ContactsPanel.Visible = false;
                    MenuButton.Pressed = false;

                    if (_isSelectingContacts)
                    {
                        _isSelectingContacts = false;
                        _selectedNewMembers.Clear();
                        AddMembersButton.Pressed = false;
                    }

                    MessageContainer.DisposeAllChildren();
                    MessageContainer.AddChild(new RichTextLabel
                    {
                        Margin = new Thickness(0, 0, 0, 5),
                        Text = Loc.GetString("nano-chat-ui-chat-window-message-loading"),
                    });

                    OnChatSelected?.Invoke(chat.Id);
                    return;
                }

                SelectChat(btn, chat, state);
            };

            ContactsListContainer.AddChild(btn);
        }

        if (_isSelectingContacts && state.CurrentChat != null)
        {
            var instruction = new Label
            {
                Text = Loc.GetString("nano-chat-ui-chat-window-add-contacts"),
                Margin = new Thickness(0, 0, 0, 10),
            };
            MessageContainer.AddChild(instruction);

            var addedAnyOptions = false;

            foreach (var contact in state.Contacts.Where(contact => !state.CurrentChat.Members.Contains(contact.Id)))
            {
                var btnText = Loc.GetString(
                    "nano-chat-ui-chat-window-contact-name-job",
                    ("name", contact.Name),
                    ("job", GetJobTitle(contact.JobTitle)));

                addedAnyOptions = true;
                var isSelected = _selectedNewMembers.Contains(contact.Id);
                var btn = new Button
                {
                    Text = btnText,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 0, 0, 5),
                    TextAlign = Label.AlignMode.Left,
                    HorizontalAlignment = HAlignment.Left,
                    ToggleMode = true,
                };

                btn.Pressed = isSelected;

                btn.OnPressed += _ =>
                {
                    if (isSelected)
                        _selectedNewMembers.Remove(contact.Id);
                    else
                        _selectedNewMembers.Add(contact.Id);

                    if (_lastState != null)
                        UpdateState(_lastState);
                };

                MessageContainer.AddChild(btn);
            }

            if (!addedAnyOptions)
            {
                MessageContainer.AddChild(new Label
                {
                    Text = Loc.GetString("nano-chat-ui-chat-window-no-available-contact"),
                    FontColorOverride = Color.Gray,
                });
            }
        }
        else
        {
            foreach (var msg in state.Messages)
                AddMessageBubble(msg);
        }
    }

    private void AddMessageBubble(NanoChatMessage msg)
    {
        var displaySender = msg.SenderName;

        if (msg.SenderId == _myId)
            displaySender = Loc.GetString("nano-chat-ui-chat-window-sender-you");
        else if (string.IsNullOrEmpty(displaySender))
            displaySender = Loc.GetString("nano-chat-ui-chat-window-sender-unknown");

        var wrapper = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var panel = new PanelContainer
        {
            StyleClasses = { StyleClass.BackgroundPanelDark },
            HorizontalExpand = false,
        };

        if (msg.SenderId == _myId)
        {
            wrapper.AddChild(new Control { HorizontalExpand = true });
            wrapper.AddChild(panel);
        }
        else
        {
            wrapper.AddChild(panel);
            wrapper.AddChild(new Control { HorizontalExpand = true });
        }

        var label = new RichTextLabel()
        {
            ToolTip = Loc.GetString("nano-chat-ui-chat-window-message-tooltip", ("time", msg.SendTime.ToString(@"hh\:mm\:ss"))),
        };
        label.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("nano-chat-ui-chat-window-message",
                ("sender", displaySender)!,
                ("content", msg.Content))));

        panel.AddChild(label);
        MessageContainer.AddChild(wrapper);
    }

    private void SelectChat(Button btn, NanoChatChat chat, NanoChatBoundUserInterfaceState state)
    {
        _selectedChat?.Pressed = false;

        _selectedChat = btn;
        _selectedChat.Pressed = true;

        ContactsPanel.Visible = false;
        MenuButton.Pressed = false;

        if (_isSelectingContacts)
        {
            _isSelectingContacts = false;
            _selectedNewMembers.Clear();
            AddMembersButton.Pressed = false;
        }

        UpdateCurrentChatDisplay(chat, true, state.Contacts);

        MessageContainer.DisposeAllChildren();
        MessageContainer.AddChild(new RichTextLabel
        {
            Margin = new Thickness(0, 0, 0, 5),
            Text = Loc.GetString("nano-chat-ui-chat-window-message-loading"),
        });

        OnChatSelected?.Invoke(chat.Id);
    }
}
