using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.Imperial.CartridgeLoader.Cartridges;
using Robust.Client.UserInterface;

namespace Content.Client.Imperial.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    public event Action? OnNotificationSwitchPressed;
    public event Action<string>? OnSendMessage;
    public event Action<string>? OnContactSelected;

    private string? _pdaCardName;

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);

        ContactsButton.OnPressed += _ =>
        {
            ContactsPanel.Visible = !ContactsPanel.Visible;
        };

        NotificationSwitch.OnPressed += _ => OnNotificationSwitchPressed?.Invoke();

        SendButton.OnPressed += _ => SendMessage();
        MessageInput.OnTextEntered += _ => SendMessage();
    }

    private void SendMessage()
    {
        var text = MessageInput.Text;
        if (string.IsNullOrWhiteSpace(text))
            return;

        AddMessageBubble(_pdaCardName, text);

        OnSendMessage?.Invoke(text);
        MessageInput.Text = string.Empty;
    }

    public void UpdateState(NanoChatBoundUserInterfaceState state)
    {
        _pdaCardName = state.PdaCardName;

        NotificationSwitch.Text = Loc.GetString(state.NotificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        CurrentContactLabel.Text = string.IsNullOrEmpty(state.CurrentContactName)
            ? Loc.GetString("nano-chat-ui-no-contact-selected")
            : state.CurrentContactName;

        ContactsListContainer.DisposeAllChildren();
        foreach (var contact in state.Contacts)
        {
            var btn = new Button
            {
                Text = contact,
                Margin = new Thickness(0, 0, 0, 2),
            };

            btn.OnPressed += _ =>
            {
                ContactsPanel.Visible = false;
                if (contact == state.CurrentContactName)
                    return;

                CurrentContactLabel.Text = contact;
                MessageContainer.DisposeAllChildren();
                MessageContainer.AddChild(new RichTextLabel
                {
                    Margin = new Thickness(0, 0, 0, 5),
                    Text = "Загрузка...",
                });
                OnContactSelected?.Invoke(contact);
            };

            ContactsListContainer.AddChild(btn);
        }

        MessageContainer.DisposeAllChildren();
        for (var index = 0; index < state.Messages.Count; index++)
        {
            var msg = state.Messages[index];

            var nextSame = (index + 1 < state.Messages.Count) && (state.Messages[index + 1].Sender == msg.Sender);
            AddMessageBubble(msg.Sender, msg.Content, nextSame);
        }
    }

    private void AddMessageBubble(string? senderName, string content, bool nextSame = false)
    {
        var displaySender = senderName;

        if (string.IsNullOrEmpty(senderName))
            displaySender = Loc.GetString("nano-chat-ui-unknown-sender");
        else if (senderName == _pdaCardName)
            displaySender = Loc.GetString("nano-chat-ui-you-text");

        var wrapper = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var panel = new PanelContainer
        {
            StyleClasses = { StyleClass.BackgroundPanelDark },
            HorizontalExpand = false,
        };

        if (senderName == _pdaCardName)
        {
            wrapper.AddChild(new Control { HorizontalExpand = true });
            wrapper.AddChild(panel);
        }
        else
        {
            wrapper.AddChild(panel);
            wrapper.AddChild(new Control { HorizontalExpand = true });
        }

        var label = new RichTextLabel();
        label.SetMessage(FormattedMessage.FromMarkupPermissive(
            $"[bold]{displaySender}:[/bold] {FormattedMessage.EscapeText(content)}"));

        panel.AddChild(label);
        MessageContainer.AddChild(wrapper);
    }
}
