using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using Content.Client.Imperial.Roadmap.UI;
using Content.Client.Stylesheets;
using Content.Shared.Imperial.ICCVar;
using Content.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Options;

[GenerateTypedNameReferences]
public sealed partial class ImperialOptionsMenuTab : Control
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private static readonly HashSet<BoundKeyFunction> ToggleFunctions = new()
        {
            EngineKeyFunctions.ShowDebugMonitors,
            EngineKeyFunctions.HideUI,
        };

    [Dependency] private readonly IInputManager _inputManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private BindButton? _currentlyRebinding;

    private readonly Dictionary<BoundKeyFunction, KeyControl> _keyControls = new();
    private readonly List<Action> _deferCommands = new();

    private Font _headerFont = default!;
    private Font _normalFont = default!;

    public ImperialOptionsMenuTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _headerFont = _resourceCache.NotoStack(variation: "Bold", size: 14);
        _normalFont = _resourceCache.NotoStack(variation: "Bold", size: 12);

        ResetAllButton.OnPressed += _ =>
        {
            _deferCommands.Add(() =>
            {
                _inputManager.ResetAllBindings();
                _inputManager.SaveToUserData();
            });
        };

        var first = true;

        void AddHeader(string headerContents)
        {
            if (!first)
            {
                KeybindsContainer.AddChild(new Control { MinSize = new Vector2(0, 8) });
            }

            first = false;
            KeybindsContainer.AddChild(new Label
            {
                Text = Loc.GetString(headerContents),
                FontColorOverride = StyleNano.NanoGold,
                FontOverride = _headerFont,
                StyleClasses = { StyleNano.StyleClassLabelHeadingBigger }
            });
        }

        void AddSubHeader(string headerContents)
        {
            if (!first)
            {
                KeybindsContainer.AddChild(new Control { MinSize = new Vector2(0, 8) });
            }

            first = false;
            KeybindsContainer.AddChild(new Label
            {
                Text = Loc.GetString(headerContents),
                FontColorOverride = Color.FromHex("#969696"),
                FontOverride = _normalFont,
                StyleClasses = { StyleNano.StyleClassLabelKeyText }
            });
        }

        void AddButton(BoundKeyFunction function)
        {
            var control = new KeyControl(this, function);
            KeybindsContainer.AddChild(control);
            _keyControls.Add(function, control);
        }

        void AddCheckBox(string checkBoxName, bool currentState, Action<BaseButton.ButtonToggledEventArgs>? callBackOnClick)
        {
            var newCheckBox = new CheckBox() { Text = Loc.GetString(checkBoxName) };
            newCheckBox.Pressed = currentState;
            newCheckBox.OnToggled += callBackOnClick;

            KeybindsContainer.AddChild(newCheckBox);
        }

        void AddColorSelector(string name, Color currentColor, Action<string>? callback)
        {
            var newColorSelector = new ColorSelectControl(this, name, currentColor, callback);

            KeybindsContainer.AddChild(newColorSelector);
        }

        AddHeader("ui-options-imperial-controls-label");
        AddButton(ContentKeyFunctions.ImperialTargetCapture);
        AddButton(ContentKeyFunctions.ImperialTargetRotate);
        AddColorSelector("ui-options-target-overlay-aim-color", Color.Red, color =>
        {
            _cfg.SetCVar(ICCVars.TargetOverlayAimColor, color);
            _cfg.SaveToFile();
        });
        AddColorSelector("ui-options-target-overlay-captured-aim-color", Color.Red, color =>
        {
            _cfg.SetCVar(ICCVars.TargetOverlayCapturedAimColor, color);
            _cfg.SaveToFile();
        });


        AddSubHeader("ui-options-imperial-controls-minigames-label");
        AddButton(ContentKeyFunctions.ImperialMinigameUp);
        AddButton(ContentKeyFunctions.ImperialMinigameLeft);
        AddButton(ContentKeyFunctions.ImperialMinigameRight);
        AddButton(ContentKeyFunctions.ImperialMinigameDown);

        foreach (var control in _keyControls.Values)
        {
            UpdateKeyControl(control);
        }
    }

    private void UpdateKeyControl(KeyControl control)
    {
        var activeBinds = _inputManager.GetKeyBindings(control.Function);

        IKeyBinding? bind1 = null;
        IKeyBinding? bind2 = null;

        if (activeBinds.Count > 0)
        {
            bind1 = activeBinds[0];

            if (activeBinds.Count > 1)
            {
                bind2 = activeBinds[1];
            }
        }

        control.BindButton1.Binding = bind1;
        control.BindButton1.UpdateText();

        control.BindButton2.Binding = bind2;
        control.BindButton2.UpdateText();

        control.BindButton2.Button.Disabled = activeBinds.Count == 0;
        control.ResetButton.Disabled = !_inputManager.IsKeyFunctionModified(control.Function);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _inputManager.FirstChanceOnKeyEvent += InputManagerOnFirstChanceOnKeyEvent;
        _inputManager.OnKeyBindingAdded += OnKeyBindAdded;
        _inputManager.OnKeyBindingRemoved += OnKeyBindRemoved;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _inputManager.FirstChanceOnKeyEvent -= InputManagerOnFirstChanceOnKeyEvent;
        _inputManager.OnKeyBindingAdded -= OnKeyBindAdded;
        _inputManager.OnKeyBindingRemoved -= OnKeyBindRemoved;
    }

    private void OnKeyBindRemoved(IKeyBinding obj)
    {
        OnKeyBindModified(obj, true);
    }

    private void OnKeyBindAdded(IKeyBinding obj)
    {
        OnKeyBindModified(obj, false);
    }

    private void OnKeyBindModified(IKeyBinding bind, bool removal)
    {
        if (!_keyControls.TryGetValue(bind.Function, out var keyControl))
        {
            return;
        }

        if (removal && _currentlyRebinding?.KeyControl == keyControl)
        {
            // Don't do update if the removal was from initiating a rebind.
            return;
        }

        UpdateKeyControl(keyControl);

        if (_currentlyRebinding == keyControl.BindButton1 || _currentlyRebinding == keyControl.BindButton2)
        {
            _currentlyRebinding = null;
        }
    }

    private void InputManagerOnFirstChanceOnKeyEvent(KeyEventArgs keyEvent, KeyEventType type)
    {
        DebugTools.Assert(IsInsideTree);

        if (_currentlyRebinding == null)
        {
            return;
        }

        keyEvent.Handle();

        if (type != KeyEventType.Up)
        {
            return;
        }

        var key = keyEvent.Key;

        // Figure out modifiers based on key event.
        // TODO: this won't allow for combinations with keys other than the standard modifier keys,
        // even though the input system totally supports it.
        var mods = new Keyboard.Key[3];
        var i = 0;
        if (keyEvent.Control && key != Keyboard.Key.Control)
        {
            mods[i] = Keyboard.Key.Control;
            i += 1;
        }

        if (keyEvent.Shift && key != Keyboard.Key.Shift)
        {
            mods[i] = Keyboard.Key.Shift;
            i += 1;
        }

        if (keyEvent.Alt && key != Keyboard.Key.Alt)
        {
            mods[i] = Keyboard.Key.Alt;
            i += 1;
        }

        // The input system can only handle 3 modifier keys so if you hold all 4 of the modifier keys
        // then system gets the shaft, I guess.
        if (keyEvent.System && i != 3 && key != Keyboard.Key.LSystem && key != Keyboard.Key.RSystem)
        {
            mods[i] = Keyboard.Key.LSystem;
        }

        var function = _currentlyRebinding.KeyControl.Function;
        var bindType = KeyBindingType.State;
        if (ToggleFunctions.Contains(function))
        {
            bindType = KeyBindingType.Toggle;
        }

        var registration = new KeyBindingRegistration
        {
            Function = function,
            BaseKey = key,
            Mod1 = mods[0],
            Mod2 = mods[1],
            Mod3 = mods[2],
            Priority = _currentlyRebinding.Binding?.Priority ?? 0,
            Type = bindType,
            CanFocus = key == Keyboard.Key.MouseLeft
                       || key == Keyboard.Key.MouseRight
                       || key == Keyboard.Key.MouseMiddle,
            CanRepeat = false
        };

        _inputManager.RegisterBinding(registration);
        // OnKeyBindModified will cause _currentlyRebinding to be reset and the UI to update.
        _inputManager.SaveToUserData();
    }

    private void RebindButtonPressed(BindButton button)
    {
        if (_currentlyRebinding != null)
        {
            return;
        }

        _currentlyRebinding = button;
        _currentlyRebinding.Button.Text = Loc.GetString("ui-options-key-prompt");

        if (button.Binding != null)
        {
            _deferCommands.Add(() =>
            {
                // Have to do defer this or else there will be an exception in InputManager.
                // Because this IS fired from an input event.
                _inputManager.RemoveBinding(button.Binding);
            });
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_deferCommands.Count == 0)
        {
            return;
        }

        foreach (var command in _deferCommands)
        {
            command();
        }

        _deferCommands.Clear();
    }

    private sealed class KeyControl : Control
    {
        public readonly BoundKeyFunction Function;
        public readonly BindButton BindButton1;
        public readonly BindButton BindButton2;
        public readonly Button ResetButton;

        public KeyControl(ImperialOptionsMenuTab parent, BoundKeyFunction function)
        {
            Function = function;
            var name = new Label
            {
                Text = Loc.GetString(
                    $"ui-options-function-{CaseConversion.PascalToKebab(function.FunctionName)}"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left
            };

            BindButton1 = new BindButton(parent, this, StyleNano.ButtonOpenRight);
            BindButton2 = new BindButton(parent, this, StyleNano.ButtonOpenLeft);
            ResetButton = new Button { Text = Loc.GetString("ui-options-color-bind-save"), StyleClasses = { StyleNano.ButtonCaution } };

            var hBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                    {
                        new Control {MinSize = new Vector2(5, 0)},
                        name,
                        BindButton1,
                        BindButton2,
                        new Control {MinSize = new Vector2(10, 0)},
                        ResetButton
                    }
            };

            ResetButton.OnPressed += args =>
            {
                parent._deferCommands.Add(() =>
                {
                    parent._inputManager.ResetBindingsFor(function);
                    parent._inputManager.SaveToUserData();
                });
            };

            AddChild(hBox);
        }
    }

    private sealed class ColorSelectControl : Control
    {
        public readonly LocId LocName;
        public readonly LineEdit ColorInput;
        public readonly BorderedPanelContainer ColorHelper;
        public readonly Button SaveButton;

        private Color _lastValidColor = default!;

        public ColorSelectControl(ImperialOptionsMenuTab parent, LocId locName, Color selectedColor, Action<string>? callback)
        {
            LocName = locName;
            var name = new Label
            {
                Text = Loc.GetString(LocName),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left
            };

            _lastValidColor = selectedColor;

            ColorInput = new LineEdit()
            {
                PlaceHolder = "#FF0000",
                Text = selectedColor.ToHex(),
                HorizontalExpand = true,
                MinWidth = 368,
                HorizontalAlignment = HAlignment.Left
            };

            SaveButton = new Button {
                Text = Loc.GetString("ui-options-color-bind-save"),
                StyleClasses = { StyleNano.ButtonCaution },
                Disabled = selectedColor == _lastValidColor
            };

            ColorHelper = new BorderedPanelContainer()
            {
                BackgroundPanelColor = _lastValidColor,
                ModulateSelfOverride = Color.White,
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                SetSize = new Vector2(25, 25),
                BorderRadius = 25,
                StyleClasses = { StyleNano.StyleClassBackgroundBaseDark }
            };

            var vBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                    {
                        ColorHelper,
                        new Control {MinSize = new Vector2(5, 0)},
                        ColorInput
                    }
            };

            var hBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                    {
                        new Control {MinSize = new Vector2(5, 0)},
                        name,
                        vBox,
                        new Control {MinSize = new Vector2(10, 0)},
                        SaveButton
                    }
            };

            ColorInput.OnTextEntered += args =>
            {
                if (!parent.TryParseColor(args.Text, out var _)) return;

                callback?.Invoke(args.Text);
                UpdateSaveButton(true);
            };

            ColorInput.OnTextChanged += args =>
            {
                if (!parent.TryParseColor(args.Text, out var parsedColor))
                {
                    UpdateSaveButton(true);

                    return;
                }

                _lastValidColor = parsedColor.Value;

                ColorHelper.BackgroundPanelColor = _lastValidColor;
                UpdateSaveButton(selectedColor == _lastValidColor);
            };

            ColorHelper.OnResized += () =>
            {
                if (ColorHelper.Width == ColorHelper.Height) return;

                ColorHelper.SetSize = new Vector2(ColorHelper.Height);
            };

            SaveButton.OnPressed += (_) =>
            {
                if (!parent.TryParseColor(ColorInput.Text, out var _)) return;

                callback?.Invoke(ColorInput.Text);
                UpdateSaveButton(true);
            };

            AddChild(hBox);
        }

        private void UpdateSaveButton(bool disabled)
        {
            SaveButton.Disabled = disabled;

            if (disabled)
            {
                SaveButton.RemoveStyleClass(StyleNano.StyleClassButtonColorGreen);
                SaveButton.AddStyleClass(StyleNano.ButtonCaution);
            }
            else
            {
                SaveButton.RemoveStyleClass(StyleNano.ButtonCaution);
                SaveButton.AddStyleClass(StyleNano.StyleClassButtonColorGreen);
            }
        }
    }

    private sealed class BindButton : Control
    {
        private readonly ImperialOptionsMenuTab _tab;
        public readonly KeyControl KeyControl;
        public readonly Button Button;
        public IKeyBinding? Binding;

        public BindButton(ImperialOptionsMenuTab tab, KeyControl keyControl, string styleClass)
        {
            _tab = tab;
            KeyControl = keyControl;
            Button = new Button { StyleClasses = { styleClass } };
            UpdateText();
            AddChild(Button);

            Button.OnPressed += args =>
            {
                tab.RebindButtonPressed(this);
            };

            Button.OnKeyBindDown += ButtonOnOnKeyBindDown;

            MinSize = new Vector2(200, 0);
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            _tab._inputManager.OnInputModeChanged += UpdateText;
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _tab._inputManager.OnInputModeChanged -= UpdateText;
        }

        private void ButtonOnOnKeyBindDown(GUIBoundKeyEventArgs args)
        {
            if (args.Function == EngineKeyFunctions.UIRightClick)
            {
                if (Binding != null)
                {
                    _tab._deferCommands.Add(() =>
                    {
                        _tab._inputManager.RemoveBinding(Binding);
                        _tab._inputManager.SaveToUserData();
                    });
                }

                args.Handle();
            }
        }

        public void UpdateText()
        {
            Button.Text = Binding?.GetKeyString() ?? Loc.GetString("ui-options-unbound");
        }
    }

    #region Helpers

    private bool TryParseColor(string str, [NotNullWhen(true)] out Color? color)
    {
        color = null;

        if (string.IsNullOrEmpty(str)) return false;

        var parsedColor = Color.TryFromHex(str);

        if (parsedColor == null)
        {
            var colorWithSeparator = Color.TryFromHex($"#{str}");

            if (colorWithSeparator == null) return false;

            color = colorWithSeparator;

            return true;
        }

        color = parsedColor;

        return true;
    }

    #endregion
}
