using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Imperial.ImperialStore.Ui.Fragments.CurrencyAmount;


[GenerateTypedNameReferences]
public sealed partial class CurrencyAmountUiFragment : BoxContainer
{
    public CurrencyAmountUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetBalance(string balanceName, string balanceCount, Color color)
    {
        BalanceName.SetMessage(balanceName, defaultColor: color);
        Balance.SetMessage(": " + balanceCount); //ULTRA UI
    }
}
