using System.Linq;
using Content.Client.Actions;
using Content.Client.Imperial.ImperialStore.Ui.Withdraw;
using Content.Client.Imperial.ImperialStore.Ui.Listing;
using Content.Client.Message;
using Content.Shared.FixedPoint;
using Content.Shared.Imperial.ImperialStore;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Imperial.ImperialStore.Ui.Fragments.CurrencyAmount;
using Robust.Client.ResourceManagement;
using Content.Client.Resources;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.ImperialStore.Ui;


[GenerateTypedNameReferences]
public sealed partial class ImperialStoreMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private ImperialStoreWithdrawWindow? _withdrawWindow;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, ImperialListingData>? OnListingButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;
    public event Action<BaseButton.ButtonEventArgs>? OnRefundAttempt;

    public Dictionary<ProtoId<ImperialCurrencyPrototype>, FixedPoint2> Balance = new();
    public string CurrentCategory = string.Empty;
    public string WithdrawButtonText = string.Empty;
    public string СurrencyTitle = string.Empty;
    public bool MinimalismModeEnable = true;

    private List<ImperialListingData> _cachedListings = new();

    private string _balanceOpenPath = "/Textures/Interface/Nano/inverted_triangle.svg.png";
    private string _balanceClosePath = "/Textures/Interface/Nano/triangle_right.png";


    public ImperialStoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MinimalismButton.TexturePath = MinimalismModeEnable ? _balanceClosePath : _balanceOpenPath;

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        RefundButton.OnButtonDown += OnRefundButtonDown;
        MinimalismButton.OnPressed += OnMinimalismToggled;

        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);
    }

    public void UpdateBalance(Dictionary<ProtoId<ImperialCurrencyPrototype>, FixedPoint2> balance)
    {
        BalanceInfo.RemoveAllChildren();
        BalanneTitleContainer.RemoveAllChildren();
        SeparatelyDrawContainer.RemoveAllChildren();

        Balance = balance;

        var currency = balance.ToDictionary(type => (type.Key, type.Value), type => _prototypeManager.Index(type.Key));
        var separatelyCurrency = currency.Where(el => el.Value.DrawSeparately);

        if (MinimalismModeEnable)
        {
            BalanceInfoTitle.SetMessage(СurrencyTitle);

            RichTextLabel? lastSeparator = null;

            foreach (var ((_, amount), proto) in currency)
            {
                if (proto.DrawSeparately) continue;

                var panel = new RichTextLabel();
                var separator = new RichTextLabel();

                panel.SetMessage(amount.ToString(), defaultColor: proto.DisplayNameColor);
                separator.SetMessage("/");

                BalanneTitleContainer.AddChild(panel);
                BalanneTitleContainer.AddChild(separator);

                lastSeparator = separator;
            }

            if (lastSeparator != null) BalanneTitleContainer.RemoveChild(lastSeparator);
        }
        else
        {
            BalanceInfoTitle.SetMessage(СurrencyTitle);

            foreach (var ((_, amount), proto) in currency)
            {
                if (proto.DrawSeparately) continue;

                var currencyBalance = new CurrencyAmountUiFragment();
                currencyBalance.SetBalance(Loc.GetString(proto.DisplayName), amount.ToString(), proto.DisplayNameColor);

                BalanceInfo.AddChild(currencyBalance);
            }
        }

        foreach (var ((_, amount), proto) in separatelyCurrency)
        {
            var currencyBalance = new CurrencyAmountUiFragment();
            currencyBalance.SetBalance(Loc.GetString(proto.DisplayName), amount.ToString(), proto.DisplayNameColor);

            SeparatelyDrawContainer.AddChild(currencyBalance);
        }

        var disabled = true;
        foreach (var type in currency)
        {
            if (type.Value.CanWithdraw && type.Value.Cash != null && type.Key.Item2 > 0)
                disabled = false;
        }

        WithdrawButton.Disabled = disabled;
    }

    public void UpdateWithdrawButton(LocId withdrawText)
    {
        WithdrawButton.Text = Loc.GetString(withdrawText);
    }

    public void UpdateListing(List<ImperialListingData> listings)
    {
        _cachedListings = listings;
        UpdateListing();
    }

    public void UpdateListing()
    {
        var sorted = _cachedListings.OrderBy(l => l.Priority).ThenBy(l => l.Cost.Values.Sum());

        // should probably chunk these out instead. to-do if this clogs the internet tubes.
        // maybe read clients prototypes instead?
        ClearListings();
        foreach (var item in sorted)
        {
            AddListingGui(item);
        }
    }

    public void SetFooterVisibility(bool visible)
    {
        TraitorFooter.Visible = visible;
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        // check if window is already open
        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        // open a new one
        _withdrawWindow = new ImperialStoreWithdrawWindow();
        _withdrawWindow.OpenCentered();

        _withdrawWindow.CreateCurrencyButtons(Balance);
        _withdrawWindow.Title = WithdrawButtonText;
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    private void OnMinimalismToggled(BaseButton.ButtonEventArgs args)
    {
        MinimalismModeEnable = !MinimalismModeEnable;
        MinimalismButton.TexturePath = MinimalismModeEnable ? _balanceClosePath : _balanceOpenPath;

        UpdateBalance(Balance);
    }

    private void OnRefundButtonDown(BaseButton.ButtonEventArgs args)
    {
        OnRefundAttempt?.Invoke(args);
    }

    private void AddListingGui(ImperialListingData listing)
    {
        if (!listing.Categories.Contains(CurrentCategory))
            return;

        var listingPrice = listing.Cost;
        var hasBalance = HasListingPrice(Balance, listingPrice);

        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        if (listing.Icon != null)
            texture = spriteSys.Frame0(listing.Icon);

        if (listing.ProductEntity != null)
        {
            if (texture == null)
                texture = spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            var action = _entityManager.System<ActionsSystem>().GetAction(actionId);
            if (action?.Comp.Icon != null)
                texture = spriteSys.Frame0(action.Value.Comp.Icon);
        }

        var newListing = new ImperialStoreListingControl(listing, GetListingPriceString(listing), hasBalance, texture);
        newListing.StoreItemBuyButton.OnButtonDown += args
            => OnListingButtonPressed?.Invoke(args, listing);

        StoreListingsContainer.AddChild(newListing);
    }

    public bool HasListingPrice(Dictionary<ProtoId<ImperialCurrencyPrototype>, FixedPoint2> currency, Dictionary<ProtoId<ImperialCurrencyPrototype>, FixedPoint2> price)
    {
        foreach (var type in price)
        {
            if (!currency.ContainsKey(type.Key))
                return false;

            if (currency[type.Key] < type.Value)
                return false;
        }
        return true;
    }

    public string GetListingPriceString(ImperialListingData listing)
    {
        var text = string.Empty;

        if (listing.Cost.Count < 1)
        {
            text = Loc.GetString("store-currency-free");
        }
        else
        {
            var ignoredCount = listing.Cost.Where(el => _prototypeManager.Index(el.Key).IgnoreInPurchaseButton).Count();
            var minimalismMode = listing.Cost.Count - ignoredCount > 1;

            foreach (var (type, amount) in listing.Cost)
            {
                var currency = _prototypeManager.Index(type);

                if (currency.IgnoreInPurchaseButton) continue;

                var standardName = Loc.GetString("store-ui-price-display", ("amount", amount), ("currency", Loc.GetString(currency.DisplayName, ("amount", amount))));
                var minimalismName = Loc.GetString("store-ui-price-display", ("amount", amount), ("currency", Loc.GetString(currency.ShortName ?? "", ("amount", amount))));

                text += minimalismMode && currency.ShortName != null ? minimalismName : standardName;
                text += ", ";
            }
        }

        return text.TrimEnd().Substring(0, text.Length - 2);
    }

    private void ClearListings()
    {
        StoreListingsContainer.Children.Clear();
    }

    public void PopulateStoreCategoryButtons(HashSet<ImperialListingData> listings)
    {
        var allCategories = new List<ImperialStoreCategoryPrototype>();
        foreach (var listing in listings)
        {
            foreach (var cat in listing.Categories)
            {
                var proto = _prototypeManager.Index(cat);
                if (!allCategories.Contains(proto))
                    allCategories.Add(proto);
            }
        }

        allCategories = allCategories.OrderBy(c => c.Priority).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCategories.All(category => category.ID != CurrentCategory))
            CurrentCategory = string.Empty;

        if (CurrentCategory == string.Empty && allCategories.Count > 0)
            CurrentCategory = allCategories.First().ID;

        CategoryListContainer.Children.Clear();
        if (allCategories.Count < 1)
            return;

        var group = new ButtonGroup();
        foreach (var proto in allCategories)
        {
            var catButton = new StoreCategoryButton
            {
                Text = Loc.GetString(proto.Name),
                Id = proto.ID,
                Pressed = proto.ID == CurrentCategory,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id);
            CategoryListContainer.AddChild(catButton);
        }
    }

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }

    public void UpdateRefund(bool allowRefund)
    {
        RefundButton.Visible = allowRefund;
    }

    private sealed class StoreCategoryButton : Button
    {
        public string? Id;
    }
}
