using System.Numerics;
using Content.Client.Imperial.UI.WindowPopOut;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.UI.Windows.BaseImperialWindow;


[Virtual, GenerateTypedNameReferences]
public partial class BaseImperialWindow : BaseWindow
{
    [ViewVariables]
    public string? HeaderText
    {
        get => HeaderLabel.Text;
        set => HeaderLabel.Text = value;
    }

    private const int DRAG_MARGIN_SIZE = 7;


    public BaseImperialWindow()
    {
        RobustXamlLoader.Load(this);

        HeaderLabel.ModulateSelfOverride = Color.FromHex("#B48528");

        CloseButton.OnPressed += _ => Close();

        ImperialWindowPopOut.Enable(this, () => HeaderText, PopOutButton); // Imperial Space

        CloseButton.OnMouseEntered += _ => CloseButton.ModulateSelfOverride = Color.DarkRed;
        CloseButton.OnMouseExited += _ => CloseButton.ModulateSelfOverride = Color.White;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (Resizable)
        {
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
                mode = DragMode.Top;
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
                mode = DragMode.Bottom;
            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
                mode |= DragMode.Left;
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
                mode |= DragMode.Right;
        }

        return mode;
    }
}
