using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Vampire.UI;

[GenerateTypedNameReferences]
public sealed partial class SelectingSubgroup : FancyWindow
{
    public event Action? OnAcceptHemomancer;
    public event Action? OnAcceptUmbrae;
    public event Action? OnAcceptGargantua;
    public SelectingSubgroup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SubgroupLabelHemomancer.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroupHemomancer-text")));
        SubgroupLabelUmbrae.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroupUmbrae-text")));
        SubgroupLabelGargantua.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroupGargantua-text")));
        SubgroupLabelTurnHemomancer.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroupHemomancer-turn")));
        SubgroupLabelTurnUmbrae.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroupUmbrae-turn")));
        SubgroupLabelTurnGargantua.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroupGargantua-turn")));
        SubgroupLabelWarning.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-warning")));

        SubgroupButtonHemomancer.OnPressed += _ => OnAcceptHemomancer?.Invoke();
        SubgroupButtonUmbrae.OnPressed += _ => OnAcceptUmbrae?.Invoke();
        SubgroupButtonGargantua.OnPressed += _ => OnAcceptGargantua?.Invoke();
    }
}
