using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Vampire.UI;

[GenerateTypedNameReferences]
public sealed partial class SelectingSubgroup : FancyWindow
{
    public event Action? OnAcceptHemomancer;
    public event Action? OnAcceptUmbrae;
    public event Action? OnAcceptGargantua;
    public SelectingSubgroup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SubgroupLabel1.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroup1-text")));
        SubgroupLabel2.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroup2-text")));
        SubgroupLabel3.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroup3-text")));
        SubgroupLabel14.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroup4-text")));
        SubgroupLabel24.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroup4-text")));
        SubgroupLabel34.SetMessage(FormattedMessage.FromMarkup(Loc.GetString("vampire-selecting-window-subgroup4-text")));

        SubgroupButton1.OnPressed += _ => OnAcceptHemomancer?.Invoke();
        SubgroupButton2.OnPressed += _ => OnAcceptUmbrae?.Invoke();
        SubgroupButton3.OnPressed += _ => OnAcceptGargantua?.Invoke();
    }
}
